// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: context.proto

package io.growing.collector.tunnel.protocol;

public interface AppDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.growing.tunnel.protocol.AppDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string package = 3;</code>
   * @return The package.
   */
  java.lang.String getPackage();
  /**
   * <code>string package = 3;</code>
   * @return The bytes for package.
   */
  com.google.protobuf.ByteString
      getPackageBytes();

  /**
   * <code>string version = 4;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <code>string version = 4;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string url_schema = 5;</code>
   * @return The urlSchema.
   */
  java.lang.String getUrlSchema();
  /**
   * <code>string url_schema = 5;</code>
   * @return The bytes for urlSchema.
   */
  com.google.protobuf.ByteString
      getUrlSchemaBytes();

  /**
   * <code>string user_agent = 6;</code>
   * @return The userAgent.
   */
  java.lang.String getUserAgent();
  /**
   * <code>string user_agent = 6;</code>
   * @return The bytes for userAgent.
   */
  com.google.protobuf.ByteString
      getUserAgentBytes();

  /**
   * <code>string channel = 7;</code>
   * @return The channel.
   */
  java.lang.String getChannel();
  /**
   * <code>string channel = 7;</code>
   * @return The bytes for channel.
   */
  com.google.protobuf.ByteString
      getChannelBytes();
}
