// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: context.proto

package io.growing.collector.tunnel.protocol;

public final class ContextProtocol {
  private ContextProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_ContextDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_ContextDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_AppDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_AppDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_DeviceDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_DeviceDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_ScreenDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_ScreenDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_OperationSystemDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_OperationSystemDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_PageDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_PageDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_ReferrerDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_ReferrerDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_LocationDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_LocationDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_NetworkDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_NetworkDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_LocaleDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_LocaleDto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcontext.proto\022\032io.growing.tunnel.proto" +
      "col\032\036google/protobuf/wrappers.proto\"\215\004\n\n" +
      "ContextDto\022/\n\003app\030\001 \001(\0132\".io.growing.tun" +
      "nel.protocol.AppDto\0225\n\006device\030\002 \001(\0132%.io" +
      ".growing.tunnel.protocol.DeviceDto\0225\n\006sc" +
      "reen\030\003 \001(\0132%.io.growing.tunnel.protocol." +
      "ScreenDto\022G\n\017operationSystem\030\004 \001(\0132..io." +
      "growing.tunnel.protocol.OperationSystemD" +
      "to\0221\n\004page\030\005 \001(\0132#.io.growing.tunnel.pro" +
      "tocol.PageDto\0229\n\010referrer\030\006 \001(\0132\'.io.gro" +
      "wing.tunnel.protocol.ReferrerDto\0229\n\010loca" +
      "tion\030\007 \001(\0132\'.io.growing.tunnel.protocol." +
      "LocationDto\0227\n\007network\030\010 \001(\0132&.io.growin" +
      "g.tunnel.protocol.NetworkDto\0225\n\006locale\030\t" +
      " \001(\0132%.io.growing.tunnel.protocol.Locale" +
      "Dto\"}\n\006AppDto\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022" +
      "\017\n\007package\030\003 \001(\t\022\017\n\007version\030\004 \001(\t\022\022\n\nurl" +
      "_schema\030\005 \001(\t\022\022\n\nuser_agent\030\006 \001(\t\022\017\n\007cha" +
      "nnel\030\007 \001(\t\"\346\001\n\tDeviceDto\022\r\n\005brand\030\001 \001(\t\022" +
      "\r\n\005model\030\002 \001(\t\022\020\n\010platform\030\003 \001(\t\022)\n\004type" +
      "\030\004 \001(\0132\033.google.protobuf.Int32Value\022\014\n\004i" +
      "mei\030\005 \001(\t\022\022\n\nandroid_id\030\006 \001(\t\022\014\n\004oaid\030\007 " +
      "\001(\t\022\035\n\025google_advertising_id\030\010 \001(\t\022\014\n\004id" +
      "fa\030\t \001(\t\022\014\n\004idfv\030\n \001(\t\022\023\n\013device_type\030\013 " +
      "\001(\t\"\257\001\n\tScreenDto\022\r\n\005width\030\001 \001(\005\022\016\n\006heig" +
      "ht\030\002 \001(\005\022\017\n\007density\030\003 \001(\005\022F\n\013orientation" +
      "\030\004 \001(\01621.io.growing.tunnel.protocol.Scre" +
      "enDto.Orientation\"*\n\013Orientation\022\014\n\010PORT" +
      "RAIT\020\000\022\r\n\tLANDSCAPE\020\001\"3\n\022OperationSystem" +
      "Dto\022\014\n\004name\030\001 \001(\t\022\017\n\007version\030\002 \001(\t\"E\n\007Pa" +
      "geDto\022\016\n\006domain\030\001 \001(\t\022\014\n\004path\030\002 \001(\t\022\r\n\005q" +
      "uery\030\003 \001(\t\022\r\n\005title\030\004 \001(\t\")\n\013ReferrerDto" +
      "\022\014\n\004from\030\001 \001(\t\022\014\n\004page\030\002 \001(\t\"2\n\013Location" +
      "Dto\022\021\n\tlongitude\030\001 \001(\001\022\020\n\010latitude\030\002 \001(\001" +
      "\"+\n\nNetworkDto\022\014\n\004type\030\001 \001(\t\022\017\n\007carrier\030" +
      "\002 \001(\t\"/\n\tLocaleDto\022\020\n\010language\030\001 \001(\t\022\020\n\010" +
      "timezone\030\002 \001(\tB9\n$io.growing.collector.t" +
      "unnel.protocolB\017ContextProtocolP\001b\006proto" +
      "3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.WrappersProto.getDescriptor(),
        });
    internal_static_io_growing_tunnel_protocol_ContextDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_growing_tunnel_protocol_ContextDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_ContextDto_descriptor,
        new java.lang.String[] { "App", "Device", "Screen", "OperationSystem", "Page", "Referrer", "Location", "Network", "Locale", });
    internal_static_io_growing_tunnel_protocol_AppDto_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_growing_tunnel_protocol_AppDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_AppDto_descriptor,
        new java.lang.String[] { "Id", "Name", "Package", "Version", "UrlSchema", "UserAgent", "Channel", });
    internal_static_io_growing_tunnel_protocol_DeviceDto_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_io_growing_tunnel_protocol_DeviceDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_DeviceDto_descriptor,
        new java.lang.String[] { "Brand", "Model", "Platform", "Type", "Imei", "AndroidId", "Oaid", "GoogleAdvertisingId", "Idfa", "Idfv", "DeviceType", });
    internal_static_io_growing_tunnel_protocol_ScreenDto_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_io_growing_tunnel_protocol_ScreenDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_ScreenDto_descriptor,
        new java.lang.String[] { "Width", "Height", "Density", "Orientation", });
    internal_static_io_growing_tunnel_protocol_OperationSystemDto_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_io_growing_tunnel_protocol_OperationSystemDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_OperationSystemDto_descriptor,
        new java.lang.String[] { "Name", "Version", });
    internal_static_io_growing_tunnel_protocol_PageDto_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_io_growing_tunnel_protocol_PageDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_PageDto_descriptor,
        new java.lang.String[] { "Domain", "Path", "Query", "Title", });
    internal_static_io_growing_tunnel_protocol_ReferrerDto_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_io_growing_tunnel_protocol_ReferrerDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_ReferrerDto_descriptor,
        new java.lang.String[] { "From", "Page", });
    internal_static_io_growing_tunnel_protocol_LocationDto_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_io_growing_tunnel_protocol_LocationDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_LocationDto_descriptor,
        new java.lang.String[] { "Longitude", "Latitude", });
    internal_static_io_growing_tunnel_protocol_NetworkDto_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_io_growing_tunnel_protocol_NetworkDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_NetworkDto_descriptor,
        new java.lang.String[] { "Type", "Carrier", });
    internal_static_io_growing_tunnel_protocol_LocaleDto_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_io_growing_tunnel_protocol_LocaleDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_LocaleDto_descriptor,
        new java.lang.String[] { "Language", "Timezone", });
    com.google.protobuf.WrappersProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
