// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: context.proto

package io.growing.collector.tunnel.protocol;

/**
 * Protobuf type {@code io.growing.tunnel.protocol.ContextDto}
 */
public final class ContextDto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.growing.tunnel.protocol.ContextDto)
    ContextDtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ContextDto.newBuilder() to construct.
  private ContextDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ContextDto() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new ContextDto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ContextDto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            io.growing.collector.tunnel.protocol.AppDto.Builder subBuilder = null;
            if (app_ != null) {
              subBuilder = app_.toBuilder();
            }
            app_ = input.readMessage(io.growing.collector.tunnel.protocol.AppDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(app_);
              app_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            io.growing.collector.tunnel.protocol.DeviceDto.Builder subBuilder = null;
            if (device_ != null) {
              subBuilder = device_.toBuilder();
            }
            device_ = input.readMessage(io.growing.collector.tunnel.protocol.DeviceDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(device_);
              device_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            io.growing.collector.tunnel.protocol.ScreenDto.Builder subBuilder = null;
            if (screen_ != null) {
              subBuilder = screen_.toBuilder();
            }
            screen_ = input.readMessage(io.growing.collector.tunnel.protocol.ScreenDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(screen_);
              screen_ = subBuilder.buildPartial();
            }

            break;
          }
          case 34: {
            io.growing.collector.tunnel.protocol.OperationSystemDto.Builder subBuilder = null;
            if (operationSystem_ != null) {
              subBuilder = operationSystem_.toBuilder();
            }
            operationSystem_ = input.readMessage(io.growing.collector.tunnel.protocol.OperationSystemDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(operationSystem_);
              operationSystem_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            io.growing.collector.tunnel.protocol.PageDto.Builder subBuilder = null;
            if (page_ != null) {
              subBuilder = page_.toBuilder();
            }
            page_ = input.readMessage(io.growing.collector.tunnel.protocol.PageDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(page_);
              page_ = subBuilder.buildPartial();
            }

            break;
          }
          case 50: {
            io.growing.collector.tunnel.protocol.ReferrerDto.Builder subBuilder = null;
            if (referrer_ != null) {
              subBuilder = referrer_.toBuilder();
            }
            referrer_ = input.readMessage(io.growing.collector.tunnel.protocol.ReferrerDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(referrer_);
              referrer_ = subBuilder.buildPartial();
            }

            break;
          }
          case 58: {
            io.growing.collector.tunnel.protocol.LocationDto.Builder subBuilder = null;
            if (location_ != null) {
              subBuilder = location_.toBuilder();
            }
            location_ = input.readMessage(io.growing.collector.tunnel.protocol.LocationDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(location_);
              location_ = subBuilder.buildPartial();
            }

            break;
          }
          case 66: {
            io.growing.collector.tunnel.protocol.NetworkDto.Builder subBuilder = null;
            if (network_ != null) {
              subBuilder = network_.toBuilder();
            }
            network_ = input.readMessage(io.growing.collector.tunnel.protocol.NetworkDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(network_);
              network_ = subBuilder.buildPartial();
            }

            break;
          }
          case 74: {
            io.growing.collector.tunnel.protocol.LocaleDto.Builder subBuilder = null;
            if (locale_ != null) {
              subBuilder = locale_.toBuilder();
            }
            locale_ = input.readMessage(io.growing.collector.tunnel.protocol.LocaleDto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(locale_);
              locale_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.growing.collector.tunnel.protocol.ContextProtocol.internal_static_io_growing_tunnel_protocol_ContextDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.growing.collector.tunnel.protocol.ContextProtocol.internal_static_io_growing_tunnel_protocol_ContextDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.growing.collector.tunnel.protocol.ContextDto.class, io.growing.collector.tunnel.protocol.ContextDto.Builder.class);
  }

  public static final int APP_FIELD_NUMBER = 1;
  private io.growing.collector.tunnel.protocol.AppDto app_;
  /**
   * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
   * @return Whether the app field is set.
   */
  @java.lang.Override
  public boolean hasApp() {
    return app_ != null;
  }
  /**
   * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
   * @return The app.
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.AppDto getApp() {
    return app_ == null ? io.growing.collector.tunnel.protocol.AppDto.getDefaultInstance() : app_;
  }
  /**
   * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.AppDtoOrBuilder getAppOrBuilder() {
    return getApp();
  }

  public static final int DEVICE_FIELD_NUMBER = 2;
  private io.growing.collector.tunnel.protocol.DeviceDto device_;
  /**
   * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
   * @return Whether the device field is set.
   */
  @java.lang.Override
  public boolean hasDevice() {
    return device_ != null;
  }
  /**
   * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
   * @return The device.
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.DeviceDto getDevice() {
    return device_ == null ? io.growing.collector.tunnel.protocol.DeviceDto.getDefaultInstance() : device_;
  }
  /**
   * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.DeviceDtoOrBuilder getDeviceOrBuilder() {
    return getDevice();
  }

  public static final int SCREEN_FIELD_NUMBER = 3;
  private io.growing.collector.tunnel.protocol.ScreenDto screen_;
  /**
   * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
   * @return Whether the screen field is set.
   */
  @java.lang.Override
  public boolean hasScreen() {
    return screen_ != null;
  }
  /**
   * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
   * @return The screen.
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.ScreenDto getScreen() {
    return screen_ == null ? io.growing.collector.tunnel.protocol.ScreenDto.getDefaultInstance() : screen_;
  }
  /**
   * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.ScreenDtoOrBuilder getScreenOrBuilder() {
    return getScreen();
  }

  public static final int OPERATIONSYSTEM_FIELD_NUMBER = 4;
  private io.growing.collector.tunnel.protocol.OperationSystemDto operationSystem_;
  /**
   * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
   * @return Whether the operationSystem field is set.
   */
  @java.lang.Override
  public boolean hasOperationSystem() {
    return operationSystem_ != null;
  }
  /**
   * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
   * @return The operationSystem.
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.OperationSystemDto getOperationSystem() {
    return operationSystem_ == null ? io.growing.collector.tunnel.protocol.OperationSystemDto.getDefaultInstance() : operationSystem_;
  }
  /**
   * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.OperationSystemDtoOrBuilder getOperationSystemOrBuilder() {
    return getOperationSystem();
  }

  public static final int PAGE_FIELD_NUMBER = 5;
  private io.growing.collector.tunnel.protocol.PageDto page_;
  /**
   * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
   * @return Whether the page field is set.
   */
  @java.lang.Override
  public boolean hasPage() {
    return page_ != null;
  }
  /**
   * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
   * @return The page.
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.PageDto getPage() {
    return page_ == null ? io.growing.collector.tunnel.protocol.PageDto.getDefaultInstance() : page_;
  }
  /**
   * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.PageDtoOrBuilder getPageOrBuilder() {
    return getPage();
  }

  public static final int REFERRER_FIELD_NUMBER = 6;
  private io.growing.collector.tunnel.protocol.ReferrerDto referrer_;
  /**
   * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
   * @return Whether the referrer field is set.
   */
  @java.lang.Override
  public boolean hasReferrer() {
    return referrer_ != null;
  }
  /**
   * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
   * @return The referrer.
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.ReferrerDto getReferrer() {
    return referrer_ == null ? io.growing.collector.tunnel.protocol.ReferrerDto.getDefaultInstance() : referrer_;
  }
  /**
   * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.ReferrerDtoOrBuilder getReferrerOrBuilder() {
    return getReferrer();
  }

  public static final int LOCATION_FIELD_NUMBER = 7;
  private io.growing.collector.tunnel.protocol.LocationDto location_;
  /**
   * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
   * @return Whether the location field is set.
   */
  @java.lang.Override
  public boolean hasLocation() {
    return location_ != null;
  }
  /**
   * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
   * @return The location.
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.LocationDto getLocation() {
    return location_ == null ? io.growing.collector.tunnel.protocol.LocationDto.getDefaultInstance() : location_;
  }
  /**
   * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.LocationDtoOrBuilder getLocationOrBuilder() {
    return getLocation();
  }

  public static final int NETWORK_FIELD_NUMBER = 8;
  private io.growing.collector.tunnel.protocol.NetworkDto network_;
  /**
   * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
   * @return Whether the network field is set.
   */
  @java.lang.Override
  public boolean hasNetwork() {
    return network_ != null;
  }
  /**
   * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
   * @return The network.
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.NetworkDto getNetwork() {
    return network_ == null ? io.growing.collector.tunnel.protocol.NetworkDto.getDefaultInstance() : network_;
  }
  /**
   * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.NetworkDtoOrBuilder getNetworkOrBuilder() {
    return getNetwork();
  }

  public static final int LOCALE_FIELD_NUMBER = 9;
  private io.growing.collector.tunnel.protocol.LocaleDto locale_;
  /**
   * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
   * @return Whether the locale field is set.
   */
  @java.lang.Override
  public boolean hasLocale() {
    return locale_ != null;
  }
  /**
   * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
   * @return The locale.
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.LocaleDto getLocale() {
    return locale_ == null ? io.growing.collector.tunnel.protocol.LocaleDto.getDefaultInstance() : locale_;
  }
  /**
   * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
   */
  @java.lang.Override
  public io.growing.collector.tunnel.protocol.LocaleDtoOrBuilder getLocaleOrBuilder() {
    return getLocale();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (app_ != null) {
      output.writeMessage(1, getApp());
    }
    if (device_ != null) {
      output.writeMessage(2, getDevice());
    }
    if (screen_ != null) {
      output.writeMessage(3, getScreen());
    }
    if (operationSystem_ != null) {
      output.writeMessage(4, getOperationSystem());
    }
    if (page_ != null) {
      output.writeMessage(5, getPage());
    }
    if (referrer_ != null) {
      output.writeMessage(6, getReferrer());
    }
    if (location_ != null) {
      output.writeMessage(7, getLocation());
    }
    if (network_ != null) {
      output.writeMessage(8, getNetwork());
    }
    if (locale_ != null) {
      output.writeMessage(9, getLocale());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (app_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getApp());
    }
    if (device_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getDevice());
    }
    if (screen_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getScreen());
    }
    if (operationSystem_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getOperationSystem());
    }
    if (page_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getPage());
    }
    if (referrer_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getReferrer());
    }
    if (location_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(7, getLocation());
    }
    if (network_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(8, getNetwork());
    }
    if (locale_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getLocale());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.growing.collector.tunnel.protocol.ContextDto)) {
      return super.equals(obj);
    }
    io.growing.collector.tunnel.protocol.ContextDto other = (io.growing.collector.tunnel.protocol.ContextDto) obj;

    if (hasApp() != other.hasApp()) return false;
    if (hasApp()) {
      if (!getApp()
          .equals(other.getApp())) return false;
    }
    if (hasDevice() != other.hasDevice()) return false;
    if (hasDevice()) {
      if (!getDevice()
          .equals(other.getDevice())) return false;
    }
    if (hasScreen() != other.hasScreen()) return false;
    if (hasScreen()) {
      if (!getScreen()
          .equals(other.getScreen())) return false;
    }
    if (hasOperationSystem() != other.hasOperationSystem()) return false;
    if (hasOperationSystem()) {
      if (!getOperationSystem()
          .equals(other.getOperationSystem())) return false;
    }
    if (hasPage() != other.hasPage()) return false;
    if (hasPage()) {
      if (!getPage()
          .equals(other.getPage())) return false;
    }
    if (hasReferrer() != other.hasReferrer()) return false;
    if (hasReferrer()) {
      if (!getReferrer()
          .equals(other.getReferrer())) return false;
    }
    if (hasLocation() != other.hasLocation()) return false;
    if (hasLocation()) {
      if (!getLocation()
          .equals(other.getLocation())) return false;
    }
    if (hasNetwork() != other.hasNetwork()) return false;
    if (hasNetwork()) {
      if (!getNetwork()
          .equals(other.getNetwork())) return false;
    }
    if (hasLocale() != other.hasLocale()) return false;
    if (hasLocale()) {
      if (!getLocale()
          .equals(other.getLocale())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasApp()) {
      hash = (37 * hash) + APP_FIELD_NUMBER;
      hash = (53 * hash) + getApp().hashCode();
    }
    if (hasDevice()) {
      hash = (37 * hash) + DEVICE_FIELD_NUMBER;
      hash = (53 * hash) + getDevice().hashCode();
    }
    if (hasScreen()) {
      hash = (37 * hash) + SCREEN_FIELD_NUMBER;
      hash = (53 * hash) + getScreen().hashCode();
    }
    if (hasOperationSystem()) {
      hash = (37 * hash) + OPERATIONSYSTEM_FIELD_NUMBER;
      hash = (53 * hash) + getOperationSystem().hashCode();
    }
    if (hasPage()) {
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage().hashCode();
    }
    if (hasReferrer()) {
      hash = (37 * hash) + REFERRER_FIELD_NUMBER;
      hash = (53 * hash) + getReferrer().hashCode();
    }
    if (hasLocation()) {
      hash = (37 * hash) + LOCATION_FIELD_NUMBER;
      hash = (53 * hash) + getLocation().hashCode();
    }
    if (hasNetwork()) {
      hash = (37 * hash) + NETWORK_FIELD_NUMBER;
      hash = (53 * hash) + getNetwork().hashCode();
    }
    if (hasLocale()) {
      hash = (37 * hash) + LOCALE_FIELD_NUMBER;
      hash = (53 * hash) + getLocale().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.growing.collector.tunnel.protocol.ContextDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.growing.collector.tunnel.protocol.ContextDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.growing.collector.tunnel.protocol.ContextDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.growing.collector.tunnel.protocol.ContextDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.growing.collector.tunnel.protocol.ContextDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.growing.collector.tunnel.protocol.ContextDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.growing.collector.tunnel.protocol.ContextDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.growing.collector.tunnel.protocol.ContextDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.growing.collector.tunnel.protocol.ContextDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.growing.collector.tunnel.protocol.ContextDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.growing.collector.tunnel.protocol.ContextDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.growing.collector.tunnel.protocol.ContextDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.growing.collector.tunnel.protocol.ContextDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.growing.tunnel.protocol.ContextDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.growing.tunnel.protocol.ContextDto)
      io.growing.collector.tunnel.protocol.ContextDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.growing.collector.tunnel.protocol.ContextProtocol.internal_static_io_growing_tunnel_protocol_ContextDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.growing.collector.tunnel.protocol.ContextProtocol.internal_static_io_growing_tunnel_protocol_ContextDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.growing.collector.tunnel.protocol.ContextDto.class, io.growing.collector.tunnel.protocol.ContextDto.Builder.class);
    }

    // Construct using io.growing.collector.tunnel.protocol.ContextDto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (appBuilder_ == null) {
        app_ = null;
      } else {
        app_ = null;
        appBuilder_ = null;
      }
      if (deviceBuilder_ == null) {
        device_ = null;
      } else {
        device_ = null;
        deviceBuilder_ = null;
      }
      if (screenBuilder_ == null) {
        screen_ = null;
      } else {
        screen_ = null;
        screenBuilder_ = null;
      }
      if (operationSystemBuilder_ == null) {
        operationSystem_ = null;
      } else {
        operationSystem_ = null;
        operationSystemBuilder_ = null;
      }
      if (pageBuilder_ == null) {
        page_ = null;
      } else {
        page_ = null;
        pageBuilder_ = null;
      }
      if (referrerBuilder_ == null) {
        referrer_ = null;
      } else {
        referrer_ = null;
        referrerBuilder_ = null;
      }
      if (locationBuilder_ == null) {
        location_ = null;
      } else {
        location_ = null;
        locationBuilder_ = null;
      }
      if (networkBuilder_ == null) {
        network_ = null;
      } else {
        network_ = null;
        networkBuilder_ = null;
      }
      if (localeBuilder_ == null) {
        locale_ = null;
      } else {
        locale_ = null;
        localeBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.growing.collector.tunnel.protocol.ContextProtocol.internal_static_io_growing_tunnel_protocol_ContextDto_descriptor;
    }

    @java.lang.Override
    public io.growing.collector.tunnel.protocol.ContextDto getDefaultInstanceForType() {
      return io.growing.collector.tunnel.protocol.ContextDto.getDefaultInstance();
    }

    @java.lang.Override
    public io.growing.collector.tunnel.protocol.ContextDto build() {
      io.growing.collector.tunnel.protocol.ContextDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.growing.collector.tunnel.protocol.ContextDto buildPartial() {
      io.growing.collector.tunnel.protocol.ContextDto result = new io.growing.collector.tunnel.protocol.ContextDto(this);
      if (appBuilder_ == null) {
        result.app_ = app_;
      } else {
        result.app_ = appBuilder_.build();
      }
      if (deviceBuilder_ == null) {
        result.device_ = device_;
      } else {
        result.device_ = deviceBuilder_.build();
      }
      if (screenBuilder_ == null) {
        result.screen_ = screen_;
      } else {
        result.screen_ = screenBuilder_.build();
      }
      if (operationSystemBuilder_ == null) {
        result.operationSystem_ = operationSystem_;
      } else {
        result.operationSystem_ = operationSystemBuilder_.build();
      }
      if (pageBuilder_ == null) {
        result.page_ = page_;
      } else {
        result.page_ = pageBuilder_.build();
      }
      if (referrerBuilder_ == null) {
        result.referrer_ = referrer_;
      } else {
        result.referrer_ = referrerBuilder_.build();
      }
      if (locationBuilder_ == null) {
        result.location_ = location_;
      } else {
        result.location_ = locationBuilder_.build();
      }
      if (networkBuilder_ == null) {
        result.network_ = network_;
      } else {
        result.network_ = networkBuilder_.build();
      }
      if (localeBuilder_ == null) {
        result.locale_ = locale_;
      } else {
        result.locale_ = localeBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.growing.collector.tunnel.protocol.ContextDto) {
        return mergeFrom((io.growing.collector.tunnel.protocol.ContextDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.growing.collector.tunnel.protocol.ContextDto other) {
      if (other == io.growing.collector.tunnel.protocol.ContextDto.getDefaultInstance()) return this;
      if (other.hasApp()) {
        mergeApp(other.getApp());
      }
      if (other.hasDevice()) {
        mergeDevice(other.getDevice());
      }
      if (other.hasScreen()) {
        mergeScreen(other.getScreen());
      }
      if (other.hasOperationSystem()) {
        mergeOperationSystem(other.getOperationSystem());
      }
      if (other.hasPage()) {
        mergePage(other.getPage());
      }
      if (other.hasReferrer()) {
        mergeReferrer(other.getReferrer());
      }
      if (other.hasLocation()) {
        mergeLocation(other.getLocation());
      }
      if (other.hasNetwork()) {
        mergeNetwork(other.getNetwork());
      }
      if (other.hasLocale()) {
        mergeLocale(other.getLocale());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.growing.collector.tunnel.protocol.ContextDto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.growing.collector.tunnel.protocol.ContextDto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private io.growing.collector.tunnel.protocol.AppDto app_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.AppDto, io.growing.collector.tunnel.protocol.AppDto.Builder, io.growing.collector.tunnel.protocol.AppDtoOrBuilder> appBuilder_;
    /**
     * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
     * @return Whether the app field is set.
     */
    public boolean hasApp() {
      return appBuilder_ != null || app_ != null;
    }
    /**
     * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
     * @return The app.
     */
    public io.growing.collector.tunnel.protocol.AppDto getApp() {
      if (appBuilder_ == null) {
        return app_ == null ? io.growing.collector.tunnel.protocol.AppDto.getDefaultInstance() : app_;
      } else {
        return appBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
     */
    public Builder setApp(io.growing.collector.tunnel.protocol.AppDto value) {
      if (appBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        app_ = value;
        onChanged();
      } else {
        appBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
     */
    public Builder setApp(
        io.growing.collector.tunnel.protocol.AppDto.Builder builderForValue) {
      if (appBuilder_ == null) {
        app_ = builderForValue.build();
        onChanged();
      } else {
        appBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
     */
    public Builder mergeApp(io.growing.collector.tunnel.protocol.AppDto value) {
      if (appBuilder_ == null) {
        if (app_ != null) {
          app_ =
            io.growing.collector.tunnel.protocol.AppDto.newBuilder(app_).mergeFrom(value).buildPartial();
        } else {
          app_ = value;
        }
        onChanged();
      } else {
        appBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
     */
    public Builder clearApp() {
      if (appBuilder_ == null) {
        app_ = null;
        onChanged();
      } else {
        app_ = null;
        appBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
     */
    public io.growing.collector.tunnel.protocol.AppDto.Builder getAppBuilder() {
      
      onChanged();
      return getAppFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
     */
    public io.growing.collector.tunnel.protocol.AppDtoOrBuilder getAppOrBuilder() {
      if (appBuilder_ != null) {
        return appBuilder_.getMessageOrBuilder();
      } else {
        return app_ == null ?
            io.growing.collector.tunnel.protocol.AppDto.getDefaultInstance() : app_;
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.AppDto, io.growing.collector.tunnel.protocol.AppDto.Builder, io.growing.collector.tunnel.protocol.AppDtoOrBuilder> 
        getAppFieldBuilder() {
      if (appBuilder_ == null) {
        appBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.growing.collector.tunnel.protocol.AppDto, io.growing.collector.tunnel.protocol.AppDto.Builder, io.growing.collector.tunnel.protocol.AppDtoOrBuilder>(
                getApp(),
                getParentForChildren(),
                isClean());
        app_ = null;
      }
      return appBuilder_;
    }

    private io.growing.collector.tunnel.protocol.DeviceDto device_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.DeviceDto, io.growing.collector.tunnel.protocol.DeviceDto.Builder, io.growing.collector.tunnel.protocol.DeviceDtoOrBuilder> deviceBuilder_;
    /**
     * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
     * @return Whether the device field is set.
     */
    public boolean hasDevice() {
      return deviceBuilder_ != null || device_ != null;
    }
    /**
     * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
     * @return The device.
     */
    public io.growing.collector.tunnel.protocol.DeviceDto getDevice() {
      if (deviceBuilder_ == null) {
        return device_ == null ? io.growing.collector.tunnel.protocol.DeviceDto.getDefaultInstance() : device_;
      } else {
        return deviceBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
     */
    public Builder setDevice(io.growing.collector.tunnel.protocol.DeviceDto value) {
      if (deviceBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        device_ = value;
        onChanged();
      } else {
        deviceBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
     */
    public Builder setDevice(
        io.growing.collector.tunnel.protocol.DeviceDto.Builder builderForValue) {
      if (deviceBuilder_ == null) {
        device_ = builderForValue.build();
        onChanged();
      } else {
        deviceBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
     */
    public Builder mergeDevice(io.growing.collector.tunnel.protocol.DeviceDto value) {
      if (deviceBuilder_ == null) {
        if (device_ != null) {
          device_ =
            io.growing.collector.tunnel.protocol.DeviceDto.newBuilder(device_).mergeFrom(value).buildPartial();
        } else {
          device_ = value;
        }
        onChanged();
      } else {
        deviceBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
     */
    public Builder clearDevice() {
      if (deviceBuilder_ == null) {
        device_ = null;
        onChanged();
      } else {
        device_ = null;
        deviceBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
     */
    public io.growing.collector.tunnel.protocol.DeviceDto.Builder getDeviceBuilder() {
      
      onChanged();
      return getDeviceFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
     */
    public io.growing.collector.tunnel.protocol.DeviceDtoOrBuilder getDeviceOrBuilder() {
      if (deviceBuilder_ != null) {
        return deviceBuilder_.getMessageOrBuilder();
      } else {
        return device_ == null ?
            io.growing.collector.tunnel.protocol.DeviceDto.getDefaultInstance() : device_;
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.DeviceDto, io.growing.collector.tunnel.protocol.DeviceDto.Builder, io.growing.collector.tunnel.protocol.DeviceDtoOrBuilder> 
        getDeviceFieldBuilder() {
      if (deviceBuilder_ == null) {
        deviceBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.growing.collector.tunnel.protocol.DeviceDto, io.growing.collector.tunnel.protocol.DeviceDto.Builder, io.growing.collector.tunnel.protocol.DeviceDtoOrBuilder>(
                getDevice(),
                getParentForChildren(),
                isClean());
        device_ = null;
      }
      return deviceBuilder_;
    }

    private io.growing.collector.tunnel.protocol.ScreenDto screen_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.ScreenDto, io.growing.collector.tunnel.protocol.ScreenDto.Builder, io.growing.collector.tunnel.protocol.ScreenDtoOrBuilder> screenBuilder_;
    /**
     * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
     * @return Whether the screen field is set.
     */
    public boolean hasScreen() {
      return screenBuilder_ != null || screen_ != null;
    }
    /**
     * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
     * @return The screen.
     */
    public io.growing.collector.tunnel.protocol.ScreenDto getScreen() {
      if (screenBuilder_ == null) {
        return screen_ == null ? io.growing.collector.tunnel.protocol.ScreenDto.getDefaultInstance() : screen_;
      } else {
        return screenBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
     */
    public Builder setScreen(io.growing.collector.tunnel.protocol.ScreenDto value) {
      if (screenBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        screen_ = value;
        onChanged();
      } else {
        screenBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
     */
    public Builder setScreen(
        io.growing.collector.tunnel.protocol.ScreenDto.Builder builderForValue) {
      if (screenBuilder_ == null) {
        screen_ = builderForValue.build();
        onChanged();
      } else {
        screenBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
     */
    public Builder mergeScreen(io.growing.collector.tunnel.protocol.ScreenDto value) {
      if (screenBuilder_ == null) {
        if (screen_ != null) {
          screen_ =
            io.growing.collector.tunnel.protocol.ScreenDto.newBuilder(screen_).mergeFrom(value).buildPartial();
        } else {
          screen_ = value;
        }
        onChanged();
      } else {
        screenBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
     */
    public Builder clearScreen() {
      if (screenBuilder_ == null) {
        screen_ = null;
        onChanged();
      } else {
        screen_ = null;
        screenBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
     */
    public io.growing.collector.tunnel.protocol.ScreenDto.Builder getScreenBuilder() {
      
      onChanged();
      return getScreenFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
     */
    public io.growing.collector.tunnel.protocol.ScreenDtoOrBuilder getScreenOrBuilder() {
      if (screenBuilder_ != null) {
        return screenBuilder_.getMessageOrBuilder();
      } else {
        return screen_ == null ?
            io.growing.collector.tunnel.protocol.ScreenDto.getDefaultInstance() : screen_;
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.ScreenDto, io.growing.collector.tunnel.protocol.ScreenDto.Builder, io.growing.collector.tunnel.protocol.ScreenDtoOrBuilder> 
        getScreenFieldBuilder() {
      if (screenBuilder_ == null) {
        screenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.growing.collector.tunnel.protocol.ScreenDto, io.growing.collector.tunnel.protocol.ScreenDto.Builder, io.growing.collector.tunnel.protocol.ScreenDtoOrBuilder>(
                getScreen(),
                getParentForChildren(),
                isClean());
        screen_ = null;
      }
      return screenBuilder_;
    }

    private io.growing.collector.tunnel.protocol.OperationSystemDto operationSystem_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.OperationSystemDto, io.growing.collector.tunnel.protocol.OperationSystemDto.Builder, io.growing.collector.tunnel.protocol.OperationSystemDtoOrBuilder> operationSystemBuilder_;
    /**
     * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
     * @return Whether the operationSystem field is set.
     */
    public boolean hasOperationSystem() {
      return operationSystemBuilder_ != null || operationSystem_ != null;
    }
    /**
     * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
     * @return The operationSystem.
     */
    public io.growing.collector.tunnel.protocol.OperationSystemDto getOperationSystem() {
      if (operationSystemBuilder_ == null) {
        return operationSystem_ == null ? io.growing.collector.tunnel.protocol.OperationSystemDto.getDefaultInstance() : operationSystem_;
      } else {
        return operationSystemBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
     */
    public Builder setOperationSystem(io.growing.collector.tunnel.protocol.OperationSystemDto value) {
      if (operationSystemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        operationSystem_ = value;
        onChanged();
      } else {
        operationSystemBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
     */
    public Builder setOperationSystem(
        io.growing.collector.tunnel.protocol.OperationSystemDto.Builder builderForValue) {
      if (operationSystemBuilder_ == null) {
        operationSystem_ = builderForValue.build();
        onChanged();
      } else {
        operationSystemBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
     */
    public Builder mergeOperationSystem(io.growing.collector.tunnel.protocol.OperationSystemDto value) {
      if (operationSystemBuilder_ == null) {
        if (operationSystem_ != null) {
          operationSystem_ =
            io.growing.collector.tunnel.protocol.OperationSystemDto.newBuilder(operationSystem_).mergeFrom(value).buildPartial();
        } else {
          operationSystem_ = value;
        }
        onChanged();
      } else {
        operationSystemBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
     */
    public Builder clearOperationSystem() {
      if (operationSystemBuilder_ == null) {
        operationSystem_ = null;
        onChanged();
      } else {
        operationSystem_ = null;
        operationSystemBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
     */
    public io.growing.collector.tunnel.protocol.OperationSystemDto.Builder getOperationSystemBuilder() {
      
      onChanged();
      return getOperationSystemFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
     */
    public io.growing.collector.tunnel.protocol.OperationSystemDtoOrBuilder getOperationSystemOrBuilder() {
      if (operationSystemBuilder_ != null) {
        return operationSystemBuilder_.getMessageOrBuilder();
      } else {
        return operationSystem_ == null ?
            io.growing.collector.tunnel.protocol.OperationSystemDto.getDefaultInstance() : operationSystem_;
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.OperationSystemDto, io.growing.collector.tunnel.protocol.OperationSystemDto.Builder, io.growing.collector.tunnel.protocol.OperationSystemDtoOrBuilder> 
        getOperationSystemFieldBuilder() {
      if (operationSystemBuilder_ == null) {
        operationSystemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.growing.collector.tunnel.protocol.OperationSystemDto, io.growing.collector.tunnel.protocol.OperationSystemDto.Builder, io.growing.collector.tunnel.protocol.OperationSystemDtoOrBuilder>(
                getOperationSystem(),
                getParentForChildren(),
                isClean());
        operationSystem_ = null;
      }
      return operationSystemBuilder_;
    }

    private io.growing.collector.tunnel.protocol.PageDto page_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.PageDto, io.growing.collector.tunnel.protocol.PageDto.Builder, io.growing.collector.tunnel.protocol.PageDtoOrBuilder> pageBuilder_;
    /**
     * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
     * @return Whether the page field is set.
     */
    public boolean hasPage() {
      return pageBuilder_ != null || page_ != null;
    }
    /**
     * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
     * @return The page.
     */
    public io.growing.collector.tunnel.protocol.PageDto getPage() {
      if (pageBuilder_ == null) {
        return page_ == null ? io.growing.collector.tunnel.protocol.PageDto.getDefaultInstance() : page_;
      } else {
        return pageBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
     */
    public Builder setPage(io.growing.collector.tunnel.protocol.PageDto value) {
      if (pageBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        page_ = value;
        onChanged();
      } else {
        pageBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
     */
    public Builder setPage(
        io.growing.collector.tunnel.protocol.PageDto.Builder builderForValue) {
      if (pageBuilder_ == null) {
        page_ = builderForValue.build();
        onChanged();
      } else {
        pageBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
     */
    public Builder mergePage(io.growing.collector.tunnel.protocol.PageDto value) {
      if (pageBuilder_ == null) {
        if (page_ != null) {
          page_ =
            io.growing.collector.tunnel.protocol.PageDto.newBuilder(page_).mergeFrom(value).buildPartial();
        } else {
          page_ = value;
        }
        onChanged();
      } else {
        pageBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
     */
    public Builder clearPage() {
      if (pageBuilder_ == null) {
        page_ = null;
        onChanged();
      } else {
        page_ = null;
        pageBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
     */
    public io.growing.collector.tunnel.protocol.PageDto.Builder getPageBuilder() {
      
      onChanged();
      return getPageFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
     */
    public io.growing.collector.tunnel.protocol.PageDtoOrBuilder getPageOrBuilder() {
      if (pageBuilder_ != null) {
        return pageBuilder_.getMessageOrBuilder();
      } else {
        return page_ == null ?
            io.growing.collector.tunnel.protocol.PageDto.getDefaultInstance() : page_;
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.PageDto, io.growing.collector.tunnel.protocol.PageDto.Builder, io.growing.collector.tunnel.protocol.PageDtoOrBuilder> 
        getPageFieldBuilder() {
      if (pageBuilder_ == null) {
        pageBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.growing.collector.tunnel.protocol.PageDto, io.growing.collector.tunnel.protocol.PageDto.Builder, io.growing.collector.tunnel.protocol.PageDtoOrBuilder>(
                getPage(),
                getParentForChildren(),
                isClean());
        page_ = null;
      }
      return pageBuilder_;
    }

    private io.growing.collector.tunnel.protocol.ReferrerDto referrer_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.ReferrerDto, io.growing.collector.tunnel.protocol.ReferrerDto.Builder, io.growing.collector.tunnel.protocol.ReferrerDtoOrBuilder> referrerBuilder_;
    /**
     * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
     * @return Whether the referrer field is set.
     */
    public boolean hasReferrer() {
      return referrerBuilder_ != null || referrer_ != null;
    }
    /**
     * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
     * @return The referrer.
     */
    public io.growing.collector.tunnel.protocol.ReferrerDto getReferrer() {
      if (referrerBuilder_ == null) {
        return referrer_ == null ? io.growing.collector.tunnel.protocol.ReferrerDto.getDefaultInstance() : referrer_;
      } else {
        return referrerBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
     */
    public Builder setReferrer(io.growing.collector.tunnel.protocol.ReferrerDto value) {
      if (referrerBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        referrer_ = value;
        onChanged();
      } else {
        referrerBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
     */
    public Builder setReferrer(
        io.growing.collector.tunnel.protocol.ReferrerDto.Builder builderForValue) {
      if (referrerBuilder_ == null) {
        referrer_ = builderForValue.build();
        onChanged();
      } else {
        referrerBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
     */
    public Builder mergeReferrer(io.growing.collector.tunnel.protocol.ReferrerDto value) {
      if (referrerBuilder_ == null) {
        if (referrer_ != null) {
          referrer_ =
            io.growing.collector.tunnel.protocol.ReferrerDto.newBuilder(referrer_).mergeFrom(value).buildPartial();
        } else {
          referrer_ = value;
        }
        onChanged();
      } else {
        referrerBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
     */
    public Builder clearReferrer() {
      if (referrerBuilder_ == null) {
        referrer_ = null;
        onChanged();
      } else {
        referrer_ = null;
        referrerBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
     */
    public io.growing.collector.tunnel.protocol.ReferrerDto.Builder getReferrerBuilder() {
      
      onChanged();
      return getReferrerFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
     */
    public io.growing.collector.tunnel.protocol.ReferrerDtoOrBuilder getReferrerOrBuilder() {
      if (referrerBuilder_ != null) {
        return referrerBuilder_.getMessageOrBuilder();
      } else {
        return referrer_ == null ?
            io.growing.collector.tunnel.protocol.ReferrerDto.getDefaultInstance() : referrer_;
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.ReferrerDto, io.growing.collector.tunnel.protocol.ReferrerDto.Builder, io.growing.collector.tunnel.protocol.ReferrerDtoOrBuilder> 
        getReferrerFieldBuilder() {
      if (referrerBuilder_ == null) {
        referrerBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.growing.collector.tunnel.protocol.ReferrerDto, io.growing.collector.tunnel.protocol.ReferrerDto.Builder, io.growing.collector.tunnel.protocol.ReferrerDtoOrBuilder>(
                getReferrer(),
                getParentForChildren(),
                isClean());
        referrer_ = null;
      }
      return referrerBuilder_;
    }

    private io.growing.collector.tunnel.protocol.LocationDto location_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.LocationDto, io.growing.collector.tunnel.protocol.LocationDto.Builder, io.growing.collector.tunnel.protocol.LocationDtoOrBuilder> locationBuilder_;
    /**
     * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
     * @return Whether the location field is set.
     */
    public boolean hasLocation() {
      return locationBuilder_ != null || location_ != null;
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
     * @return The location.
     */
    public io.growing.collector.tunnel.protocol.LocationDto getLocation() {
      if (locationBuilder_ == null) {
        return location_ == null ? io.growing.collector.tunnel.protocol.LocationDto.getDefaultInstance() : location_;
      } else {
        return locationBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
     */
    public Builder setLocation(io.growing.collector.tunnel.protocol.LocationDto value) {
      if (locationBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        location_ = value;
        onChanged();
      } else {
        locationBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
     */
    public Builder setLocation(
        io.growing.collector.tunnel.protocol.LocationDto.Builder builderForValue) {
      if (locationBuilder_ == null) {
        location_ = builderForValue.build();
        onChanged();
      } else {
        locationBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
     */
    public Builder mergeLocation(io.growing.collector.tunnel.protocol.LocationDto value) {
      if (locationBuilder_ == null) {
        if (location_ != null) {
          location_ =
            io.growing.collector.tunnel.protocol.LocationDto.newBuilder(location_).mergeFrom(value).buildPartial();
        } else {
          location_ = value;
        }
        onChanged();
      } else {
        locationBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
     */
    public Builder clearLocation() {
      if (locationBuilder_ == null) {
        location_ = null;
        onChanged();
      } else {
        location_ = null;
        locationBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
     */
    public io.growing.collector.tunnel.protocol.LocationDto.Builder getLocationBuilder() {
      
      onChanged();
      return getLocationFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
     */
    public io.growing.collector.tunnel.protocol.LocationDtoOrBuilder getLocationOrBuilder() {
      if (locationBuilder_ != null) {
        return locationBuilder_.getMessageOrBuilder();
      } else {
        return location_ == null ?
            io.growing.collector.tunnel.protocol.LocationDto.getDefaultInstance() : location_;
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.LocationDto, io.growing.collector.tunnel.protocol.LocationDto.Builder, io.growing.collector.tunnel.protocol.LocationDtoOrBuilder> 
        getLocationFieldBuilder() {
      if (locationBuilder_ == null) {
        locationBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.growing.collector.tunnel.protocol.LocationDto, io.growing.collector.tunnel.protocol.LocationDto.Builder, io.growing.collector.tunnel.protocol.LocationDtoOrBuilder>(
                getLocation(),
                getParentForChildren(),
                isClean());
        location_ = null;
      }
      return locationBuilder_;
    }

    private io.growing.collector.tunnel.protocol.NetworkDto network_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.NetworkDto, io.growing.collector.tunnel.protocol.NetworkDto.Builder, io.growing.collector.tunnel.protocol.NetworkDtoOrBuilder> networkBuilder_;
    /**
     * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
     * @return Whether the network field is set.
     */
    public boolean hasNetwork() {
      return networkBuilder_ != null || network_ != null;
    }
    /**
     * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
     * @return The network.
     */
    public io.growing.collector.tunnel.protocol.NetworkDto getNetwork() {
      if (networkBuilder_ == null) {
        return network_ == null ? io.growing.collector.tunnel.protocol.NetworkDto.getDefaultInstance() : network_;
      } else {
        return networkBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
     */
    public Builder setNetwork(io.growing.collector.tunnel.protocol.NetworkDto value) {
      if (networkBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        network_ = value;
        onChanged();
      } else {
        networkBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
     */
    public Builder setNetwork(
        io.growing.collector.tunnel.protocol.NetworkDto.Builder builderForValue) {
      if (networkBuilder_ == null) {
        network_ = builderForValue.build();
        onChanged();
      } else {
        networkBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
     */
    public Builder mergeNetwork(io.growing.collector.tunnel.protocol.NetworkDto value) {
      if (networkBuilder_ == null) {
        if (network_ != null) {
          network_ =
            io.growing.collector.tunnel.protocol.NetworkDto.newBuilder(network_).mergeFrom(value).buildPartial();
        } else {
          network_ = value;
        }
        onChanged();
      } else {
        networkBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
     */
    public Builder clearNetwork() {
      if (networkBuilder_ == null) {
        network_ = null;
        onChanged();
      } else {
        network_ = null;
        networkBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
     */
    public io.growing.collector.tunnel.protocol.NetworkDto.Builder getNetworkBuilder() {
      
      onChanged();
      return getNetworkFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
     */
    public io.growing.collector.tunnel.protocol.NetworkDtoOrBuilder getNetworkOrBuilder() {
      if (networkBuilder_ != null) {
        return networkBuilder_.getMessageOrBuilder();
      } else {
        return network_ == null ?
            io.growing.collector.tunnel.protocol.NetworkDto.getDefaultInstance() : network_;
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.NetworkDto, io.growing.collector.tunnel.protocol.NetworkDto.Builder, io.growing.collector.tunnel.protocol.NetworkDtoOrBuilder> 
        getNetworkFieldBuilder() {
      if (networkBuilder_ == null) {
        networkBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.growing.collector.tunnel.protocol.NetworkDto, io.growing.collector.tunnel.protocol.NetworkDto.Builder, io.growing.collector.tunnel.protocol.NetworkDtoOrBuilder>(
                getNetwork(),
                getParentForChildren(),
                isClean());
        network_ = null;
      }
      return networkBuilder_;
    }

    private io.growing.collector.tunnel.protocol.LocaleDto locale_;
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.LocaleDto, io.growing.collector.tunnel.protocol.LocaleDto.Builder, io.growing.collector.tunnel.protocol.LocaleDtoOrBuilder> localeBuilder_;
    /**
     * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
     * @return Whether the locale field is set.
     */
    public boolean hasLocale() {
      return localeBuilder_ != null || locale_ != null;
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
     * @return The locale.
     */
    public io.growing.collector.tunnel.protocol.LocaleDto getLocale() {
      if (localeBuilder_ == null) {
        return locale_ == null ? io.growing.collector.tunnel.protocol.LocaleDto.getDefaultInstance() : locale_;
      } else {
        return localeBuilder_.getMessage();
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
     */
    public Builder setLocale(io.growing.collector.tunnel.protocol.LocaleDto value) {
      if (localeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        locale_ = value;
        onChanged();
      } else {
        localeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
     */
    public Builder setLocale(
        io.growing.collector.tunnel.protocol.LocaleDto.Builder builderForValue) {
      if (localeBuilder_ == null) {
        locale_ = builderForValue.build();
        onChanged();
      } else {
        localeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
     */
    public Builder mergeLocale(io.growing.collector.tunnel.protocol.LocaleDto value) {
      if (localeBuilder_ == null) {
        if (locale_ != null) {
          locale_ =
            io.growing.collector.tunnel.protocol.LocaleDto.newBuilder(locale_).mergeFrom(value).buildPartial();
        } else {
          locale_ = value;
        }
        onChanged();
      } else {
        localeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
     */
    public Builder clearLocale() {
      if (localeBuilder_ == null) {
        locale_ = null;
        onChanged();
      } else {
        locale_ = null;
        localeBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
     */
    public io.growing.collector.tunnel.protocol.LocaleDto.Builder getLocaleBuilder() {
      
      onChanged();
      return getLocaleFieldBuilder().getBuilder();
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
     */
    public io.growing.collector.tunnel.protocol.LocaleDtoOrBuilder getLocaleOrBuilder() {
      if (localeBuilder_ != null) {
        return localeBuilder_.getMessageOrBuilder();
      } else {
        return locale_ == null ?
            io.growing.collector.tunnel.protocol.LocaleDto.getDefaultInstance() : locale_;
      }
    }
    /**
     * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        io.growing.collector.tunnel.protocol.LocaleDto, io.growing.collector.tunnel.protocol.LocaleDto.Builder, io.growing.collector.tunnel.protocol.LocaleDtoOrBuilder> 
        getLocaleFieldBuilder() {
      if (localeBuilder_ == null) {
        localeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            io.growing.collector.tunnel.protocol.LocaleDto, io.growing.collector.tunnel.protocol.LocaleDto.Builder, io.growing.collector.tunnel.protocol.LocaleDtoOrBuilder>(
                getLocale(),
                getParentForChildren(),
                isClean());
        locale_ = null;
      }
      return localeBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.growing.tunnel.protocol.ContextDto)
  }

  // @@protoc_insertion_point(class_scope:io.growing.tunnel.protocol.ContextDto)
  private static final io.growing.collector.tunnel.protocol.ContextDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.growing.collector.tunnel.protocol.ContextDto();
  }

  public static io.growing.collector.tunnel.protocol.ContextDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ContextDto>
      PARSER = new com.google.protobuf.AbstractParser<ContextDto>() {
    @java.lang.Override
    public ContextDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ContextDto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ContextDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ContextDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.growing.collector.tunnel.protocol.ContextDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

