// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: context.proto

package io.growing.collector.tunnel.protocol;

public interface ContextDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.growing.tunnel.protocol.ContextDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
   * @return Whether the app field is set.
   */
  boolean hasApp();
  /**
   * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
   * @return The app.
   */
  io.growing.collector.tunnel.protocol.AppDto getApp();
  /**
   * <code>.io.growing.tunnel.protocol.AppDto app = 1;</code>
   */
  io.growing.collector.tunnel.protocol.AppDtoOrBuilder getAppOrBuilder();

  /**
   * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
   * @return Whether the device field is set.
   */
  boolean hasDevice();
  /**
   * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
   * @return The device.
   */
  io.growing.collector.tunnel.protocol.DeviceDto getDevice();
  /**
   * <code>.io.growing.tunnel.protocol.DeviceDto device = 2;</code>
   */
  io.growing.collector.tunnel.protocol.DeviceDtoOrBuilder getDeviceOrBuilder();

  /**
   * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
   * @return Whether the screen field is set.
   */
  boolean hasScreen();
  /**
   * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
   * @return The screen.
   */
  io.growing.collector.tunnel.protocol.ScreenDto getScreen();
  /**
   * <code>.io.growing.tunnel.protocol.ScreenDto screen = 3;</code>
   */
  io.growing.collector.tunnel.protocol.ScreenDtoOrBuilder getScreenOrBuilder();

  /**
   * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
   * @return Whether the operationSystem field is set.
   */
  boolean hasOperationSystem();
  /**
   * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
   * @return The operationSystem.
   */
  io.growing.collector.tunnel.protocol.OperationSystemDto getOperationSystem();
  /**
   * <code>.io.growing.tunnel.protocol.OperationSystemDto operationSystem = 4;</code>
   */
  io.growing.collector.tunnel.protocol.OperationSystemDtoOrBuilder getOperationSystemOrBuilder();

  /**
   * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
   * @return The page.
   */
  io.growing.collector.tunnel.protocol.PageDto getPage();
  /**
   * <code>.io.growing.tunnel.protocol.PageDto page = 5;</code>
   */
  io.growing.collector.tunnel.protocol.PageDtoOrBuilder getPageOrBuilder();

  /**
   * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
   * @return Whether the referrer field is set.
   */
  boolean hasReferrer();
  /**
   * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
   * @return The referrer.
   */
  io.growing.collector.tunnel.protocol.ReferrerDto getReferrer();
  /**
   * <code>.io.growing.tunnel.protocol.ReferrerDto referrer = 6;</code>
   */
  io.growing.collector.tunnel.protocol.ReferrerDtoOrBuilder getReferrerOrBuilder();

  /**
   * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
   * @return Whether the location field is set.
   */
  boolean hasLocation();
  /**
   * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
   * @return The location.
   */
  io.growing.collector.tunnel.protocol.LocationDto getLocation();
  /**
   * <code>.io.growing.tunnel.protocol.LocationDto location = 7;</code>
   */
  io.growing.collector.tunnel.protocol.LocationDtoOrBuilder getLocationOrBuilder();

  /**
   * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
   * @return Whether the network field is set.
   */
  boolean hasNetwork();
  /**
   * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
   * @return The network.
   */
  io.growing.collector.tunnel.protocol.NetworkDto getNetwork();
  /**
   * <code>.io.growing.tunnel.protocol.NetworkDto network = 8;</code>
   */
  io.growing.collector.tunnel.protocol.NetworkDtoOrBuilder getNetworkOrBuilder();

  /**
   * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
   * @return Whether the locale field is set.
   */
  boolean hasLocale();
  /**
   * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
   * @return The locale.
   */
  io.growing.collector.tunnel.protocol.LocaleDto getLocale();
  /**
   * <code>.io.growing.tunnel.protocol.LocaleDto locale = 9;</code>
   */
  io.growing.collector.tunnel.protocol.LocaleDtoOrBuilder getLocaleOrBuilder();
}
