// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: context.proto

package io.growing.collector.tunnel.protocol;

/**
 * Protobuf type {@code io.growing.tunnel.protocol.DeviceDto}
 */
public final class DeviceDto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:io.growing.tunnel.protocol.DeviceDto)
    DeviceDtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use DeviceDto.newBuilder() to construct.
  private DeviceDto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private DeviceDto() {
    brand_ = "";
    model_ = "";
    platform_ = "";
    imei_ = "";
    androidId_ = "";
    oaid_ = "";
    googleAdvertisingId_ = "";
    idfa_ = "";
    idfv_ = "";
    deviceType_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new DeviceDto();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private DeviceDto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            brand_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            model_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            platform_ = s;
            break;
          }
          case 34: {
            com.google.protobuf.Int32Value.Builder subBuilder = null;
            if (type_ != null) {
              subBuilder = type_.toBuilder();
            }
            type_ = input.readMessage(com.google.protobuf.Int32Value.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(type_);
              type_ = subBuilder.buildPartial();
            }

            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            imei_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            androidId_ = s;
            break;
          }
          case 58: {
            java.lang.String s = input.readStringRequireUtf8();

            oaid_ = s;
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            googleAdvertisingId_ = s;
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            idfa_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            idfv_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            deviceType_ = s;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.growing.collector.tunnel.protocol.ContextProtocol.internal_static_io_growing_tunnel_protocol_DeviceDto_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.growing.collector.tunnel.protocol.ContextProtocol.internal_static_io_growing_tunnel_protocol_DeviceDto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.growing.collector.tunnel.protocol.DeviceDto.class, io.growing.collector.tunnel.protocol.DeviceDto.Builder.class);
  }

  public static final int BRAND_FIELD_NUMBER = 1;
  private volatile java.lang.Object brand_;
  /**
   * <code>string brand = 1;</code>
   * @return The brand.
   */
  @java.lang.Override
  public java.lang.String getBrand() {
    java.lang.Object ref = brand_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      brand_ = s;
      return s;
    }
  }
  /**
   * <code>string brand = 1;</code>
   * @return The bytes for brand.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBrandBytes() {
    java.lang.Object ref = brand_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      brand_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MODEL_FIELD_NUMBER = 2;
  private volatile java.lang.Object model_;
  /**
   * <code>string model = 2;</code>
   * @return The model.
   */
  @java.lang.Override
  public java.lang.String getModel() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      model_ = s;
      return s;
    }
  }
  /**
   * <code>string model = 2;</code>
   * @return The bytes for model.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getModelBytes() {
    java.lang.Object ref = model_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      model_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PLATFORM_FIELD_NUMBER = 3;
  private volatile java.lang.Object platform_;
  /**
   * <code>string platform = 3;</code>
   * @return The platform.
   */
  @java.lang.Override
  public java.lang.String getPlatform() {
    java.lang.Object ref = platform_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      platform_ = s;
      return s;
    }
  }
  /**
   * <code>string platform = 3;</code>
   * @return The bytes for platform.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPlatformBytes() {
    java.lang.Object ref = platform_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      platform_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 4;
  private com.google.protobuf.Int32Value type_;
  /**
   * <pre>
   * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
   * 兼容3.0测量协议 device_type 为 string enums
   * </pre>
   *
   * <code>.google.protobuf.Int32Value type = 4;</code>
   * @return Whether the type field is set.
   */
  @java.lang.Override
  public boolean hasType() {
    return type_ != null;
  }
  /**
   * <pre>
   * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
   * 兼容3.0测量协议 device_type 为 string enums
   * </pre>
   *
   * <code>.google.protobuf.Int32Value type = 4;</code>
   * @return The type.
   */
  @java.lang.Override
  public com.google.protobuf.Int32Value getType() {
    return type_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : type_;
  }
  /**
   * <pre>
   * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
   * 兼容3.0测量协议 device_type 为 string enums
   * </pre>
   *
   * <code>.google.protobuf.Int32Value type = 4;</code>
   */
  @java.lang.Override
  public com.google.protobuf.Int32ValueOrBuilder getTypeOrBuilder() {
    return getType();
  }

  public static final int IMEI_FIELD_NUMBER = 5;
  private volatile java.lang.Object imei_;
  /**
   * <code>string imei = 5;</code>
   * @return The imei.
   */
  @java.lang.Override
  public java.lang.String getImei() {
    java.lang.Object ref = imei_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      imei_ = s;
      return s;
    }
  }
  /**
   * <code>string imei = 5;</code>
   * @return The bytes for imei.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getImeiBytes() {
    java.lang.Object ref = imei_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      imei_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ANDROID_ID_FIELD_NUMBER = 6;
  private volatile java.lang.Object androidId_;
  /**
   * <code>string android_id = 6;</code>
   * @return The androidId.
   */
  @java.lang.Override
  public java.lang.String getAndroidId() {
    java.lang.Object ref = androidId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      androidId_ = s;
      return s;
    }
  }
  /**
   * <code>string android_id = 6;</code>
   * @return The bytes for androidId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAndroidIdBytes() {
    java.lang.Object ref = androidId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      androidId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OAID_FIELD_NUMBER = 7;
  private volatile java.lang.Object oaid_;
  /**
   * <code>string oaid = 7;</code>
   * @return The oaid.
   */
  @java.lang.Override
  public java.lang.String getOaid() {
    java.lang.Object ref = oaid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      oaid_ = s;
      return s;
    }
  }
  /**
   * <code>string oaid = 7;</code>
   * @return The bytes for oaid.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getOaidBytes() {
    java.lang.Object ref = oaid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      oaid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int GOOGLE_ADVERTISING_ID_FIELD_NUMBER = 8;
  private volatile java.lang.Object googleAdvertisingId_;
  /**
   * <code>string google_advertising_id = 8;</code>
   * @return The googleAdvertisingId.
   */
  @java.lang.Override
  public java.lang.String getGoogleAdvertisingId() {
    java.lang.Object ref = googleAdvertisingId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      googleAdvertisingId_ = s;
      return s;
    }
  }
  /**
   * <code>string google_advertising_id = 8;</code>
   * @return The bytes for googleAdvertisingId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getGoogleAdvertisingIdBytes() {
    java.lang.Object ref = googleAdvertisingId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      googleAdvertisingId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDFA_FIELD_NUMBER = 9;
  private volatile java.lang.Object idfa_;
  /**
   * <code>string idfa = 9;</code>
   * @return The idfa.
   */
  @java.lang.Override
  public java.lang.String getIdfa() {
    java.lang.Object ref = idfa_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idfa_ = s;
      return s;
    }
  }
  /**
   * <code>string idfa = 9;</code>
   * @return The bytes for idfa.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdfaBytes() {
    java.lang.Object ref = idfa_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idfa_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int IDFV_FIELD_NUMBER = 10;
  private volatile java.lang.Object idfv_;
  /**
   * <code>string idfv = 10;</code>
   * @return The idfv.
   */
  @java.lang.Override
  public java.lang.String getIdfv() {
    java.lang.Object ref = idfv_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      idfv_ = s;
      return s;
    }
  }
  /**
   * <code>string idfv = 10;</code>
   * @return The bytes for idfv.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdfvBytes() {
    java.lang.Object ref = idfv_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      idfv_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DEVICE_TYPE_FIELD_NUMBER = 11;
  private volatile java.lang.Object deviceType_;
  /**
   * <code>string device_type = 11;</code>
   * @return The deviceType.
   */
  @java.lang.Override
  public java.lang.String getDeviceType() {
    java.lang.Object ref = deviceType_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      deviceType_ = s;
      return s;
    }
  }
  /**
   * <code>string device_type = 11;</code>
   * @return The bytes for deviceType.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDeviceTypeBytes() {
    java.lang.Object ref = deviceType_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      deviceType_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getBrandBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, brand_);
    }
    if (!getModelBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, model_);
    }
    if (!getPlatformBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, platform_);
    }
    if (type_ != null) {
      output.writeMessage(4, getType());
    }
    if (!getImeiBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, imei_);
    }
    if (!getAndroidIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, androidId_);
    }
    if (!getOaidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 7, oaid_);
    }
    if (!getGoogleAdvertisingIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, googleAdvertisingId_);
    }
    if (!getIdfaBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, idfa_);
    }
    if (!getIdfvBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, idfv_);
    }
    if (!getDeviceTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, deviceType_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getBrandBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, brand_);
    }
    if (!getModelBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, model_);
    }
    if (!getPlatformBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, platform_);
    }
    if (type_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getType());
    }
    if (!getImeiBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, imei_);
    }
    if (!getAndroidIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, androidId_);
    }
    if (!getOaidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, oaid_);
    }
    if (!getGoogleAdvertisingIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, googleAdvertisingId_);
    }
    if (!getIdfaBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, idfa_);
    }
    if (!getIdfvBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, idfv_);
    }
    if (!getDeviceTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, deviceType_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.growing.collector.tunnel.protocol.DeviceDto)) {
      return super.equals(obj);
    }
    io.growing.collector.tunnel.protocol.DeviceDto other = (io.growing.collector.tunnel.protocol.DeviceDto) obj;

    if (!getBrand()
        .equals(other.getBrand())) return false;
    if (!getModel()
        .equals(other.getModel())) return false;
    if (!getPlatform()
        .equals(other.getPlatform())) return false;
    if (hasType() != other.hasType()) return false;
    if (hasType()) {
      if (!getType()
          .equals(other.getType())) return false;
    }
    if (!getImei()
        .equals(other.getImei())) return false;
    if (!getAndroidId()
        .equals(other.getAndroidId())) return false;
    if (!getOaid()
        .equals(other.getOaid())) return false;
    if (!getGoogleAdvertisingId()
        .equals(other.getGoogleAdvertisingId())) return false;
    if (!getIdfa()
        .equals(other.getIdfa())) return false;
    if (!getIdfv()
        .equals(other.getIdfv())) return false;
    if (!getDeviceType()
        .equals(other.getDeviceType())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BRAND_FIELD_NUMBER;
    hash = (53 * hash) + getBrand().hashCode();
    hash = (37 * hash) + MODEL_FIELD_NUMBER;
    hash = (53 * hash) + getModel().hashCode();
    hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
    hash = (53 * hash) + getPlatform().hashCode();
    if (hasType()) {
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
    }
    hash = (37 * hash) + IMEI_FIELD_NUMBER;
    hash = (53 * hash) + getImei().hashCode();
    hash = (37 * hash) + ANDROID_ID_FIELD_NUMBER;
    hash = (53 * hash) + getAndroidId().hashCode();
    hash = (37 * hash) + OAID_FIELD_NUMBER;
    hash = (53 * hash) + getOaid().hashCode();
    hash = (37 * hash) + GOOGLE_ADVERTISING_ID_FIELD_NUMBER;
    hash = (53 * hash) + getGoogleAdvertisingId().hashCode();
    hash = (37 * hash) + IDFA_FIELD_NUMBER;
    hash = (53 * hash) + getIdfa().hashCode();
    hash = (37 * hash) + IDFV_FIELD_NUMBER;
    hash = (53 * hash) + getIdfv().hashCode();
    hash = (37 * hash) + DEVICE_TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getDeviceType().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.growing.collector.tunnel.protocol.DeviceDto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.growing.collector.tunnel.protocol.DeviceDto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.growing.collector.tunnel.protocol.DeviceDto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.growing.collector.tunnel.protocol.DeviceDto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.growing.collector.tunnel.protocol.DeviceDto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.growing.collector.tunnel.protocol.DeviceDto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.growing.collector.tunnel.protocol.DeviceDto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.growing.collector.tunnel.protocol.DeviceDto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.growing.collector.tunnel.protocol.DeviceDto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.growing.collector.tunnel.protocol.DeviceDto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.growing.collector.tunnel.protocol.DeviceDto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.growing.collector.tunnel.protocol.DeviceDto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.growing.collector.tunnel.protocol.DeviceDto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code io.growing.tunnel.protocol.DeviceDto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:io.growing.tunnel.protocol.DeviceDto)
      io.growing.collector.tunnel.protocol.DeviceDtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.growing.collector.tunnel.protocol.ContextProtocol.internal_static_io_growing_tunnel_protocol_DeviceDto_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.growing.collector.tunnel.protocol.ContextProtocol.internal_static_io_growing_tunnel_protocol_DeviceDto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.growing.collector.tunnel.protocol.DeviceDto.class, io.growing.collector.tunnel.protocol.DeviceDto.Builder.class);
    }

    // Construct using io.growing.collector.tunnel.protocol.DeviceDto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      brand_ = "";

      model_ = "";

      platform_ = "";

      if (typeBuilder_ == null) {
        type_ = null;
      } else {
        type_ = null;
        typeBuilder_ = null;
      }
      imei_ = "";

      androidId_ = "";

      oaid_ = "";

      googleAdvertisingId_ = "";

      idfa_ = "";

      idfv_ = "";

      deviceType_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.growing.collector.tunnel.protocol.ContextProtocol.internal_static_io_growing_tunnel_protocol_DeviceDto_descriptor;
    }

    @java.lang.Override
    public io.growing.collector.tunnel.protocol.DeviceDto getDefaultInstanceForType() {
      return io.growing.collector.tunnel.protocol.DeviceDto.getDefaultInstance();
    }

    @java.lang.Override
    public io.growing.collector.tunnel.protocol.DeviceDto build() {
      io.growing.collector.tunnel.protocol.DeviceDto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.growing.collector.tunnel.protocol.DeviceDto buildPartial() {
      io.growing.collector.tunnel.protocol.DeviceDto result = new io.growing.collector.tunnel.protocol.DeviceDto(this);
      result.brand_ = brand_;
      result.model_ = model_;
      result.platform_ = platform_;
      if (typeBuilder_ == null) {
        result.type_ = type_;
      } else {
        result.type_ = typeBuilder_.build();
      }
      result.imei_ = imei_;
      result.androidId_ = androidId_;
      result.oaid_ = oaid_;
      result.googleAdvertisingId_ = googleAdvertisingId_;
      result.idfa_ = idfa_;
      result.idfv_ = idfv_;
      result.deviceType_ = deviceType_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.growing.collector.tunnel.protocol.DeviceDto) {
        return mergeFrom((io.growing.collector.tunnel.protocol.DeviceDto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.growing.collector.tunnel.protocol.DeviceDto other) {
      if (other == io.growing.collector.tunnel.protocol.DeviceDto.getDefaultInstance()) return this;
      if (!other.getBrand().isEmpty()) {
        brand_ = other.brand_;
        onChanged();
      }
      if (!other.getModel().isEmpty()) {
        model_ = other.model_;
        onChanged();
      }
      if (!other.getPlatform().isEmpty()) {
        platform_ = other.platform_;
        onChanged();
      }
      if (other.hasType()) {
        mergeType(other.getType());
      }
      if (!other.getImei().isEmpty()) {
        imei_ = other.imei_;
        onChanged();
      }
      if (!other.getAndroidId().isEmpty()) {
        androidId_ = other.androidId_;
        onChanged();
      }
      if (!other.getOaid().isEmpty()) {
        oaid_ = other.oaid_;
        onChanged();
      }
      if (!other.getGoogleAdvertisingId().isEmpty()) {
        googleAdvertisingId_ = other.googleAdvertisingId_;
        onChanged();
      }
      if (!other.getIdfa().isEmpty()) {
        idfa_ = other.idfa_;
        onChanged();
      }
      if (!other.getIdfv().isEmpty()) {
        idfv_ = other.idfv_;
        onChanged();
      }
      if (!other.getDeviceType().isEmpty()) {
        deviceType_ = other.deviceType_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.growing.collector.tunnel.protocol.DeviceDto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.growing.collector.tunnel.protocol.DeviceDto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object brand_ = "";
    /**
     * <code>string brand = 1;</code>
     * @return The brand.
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string brand = 1;</code>
     * @return The bytes for brand.
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string brand = 1;</code>
     * @param value The brand to set.
     * @return This builder for chaining.
     */
    public Builder setBrand(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      brand_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string brand = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBrand() {
      
      brand_ = getDefaultInstance().getBrand();
      onChanged();
      return this;
    }
    /**
     * <code>string brand = 1;</code>
     * @param value The bytes for brand to set.
     * @return This builder for chaining.
     */
    public Builder setBrandBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      brand_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object model_ = "";
    /**
     * <code>string model = 2;</code>
     * @return The model.
     */
    public java.lang.String getModel() {
      java.lang.Object ref = model_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        model_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string model = 2;</code>
     * @return The bytes for model.
     */
    public com.google.protobuf.ByteString
        getModelBytes() {
      java.lang.Object ref = model_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        model_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string model = 2;</code>
     * @param value The model to set.
     * @return This builder for chaining.
     */
    public Builder setModel(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      model_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string model = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearModel() {
      
      model_ = getDefaultInstance().getModel();
      onChanged();
      return this;
    }
    /**
     * <code>string model = 2;</code>
     * @param value The bytes for model to set.
     * @return This builder for chaining.
     */
    public Builder setModelBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      model_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object platform_ = "";
    /**
     * <code>string platform = 3;</code>
     * @return The platform.
     */
    public java.lang.String getPlatform() {
      java.lang.Object ref = platform_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        platform_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string platform = 3;</code>
     * @return The bytes for platform.
     */
    public com.google.protobuf.ByteString
        getPlatformBytes() {
      java.lang.Object ref = platform_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        platform_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string platform = 3;</code>
     * @param value The platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatform(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      platform_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string platform = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatform() {
      
      platform_ = getDefaultInstance().getPlatform();
      onChanged();
      return this;
    }
    /**
     * <code>string platform = 3;</code>
     * @param value The bytes for platform to set.
     * @return This builder for chaining.
     */
    public Builder setPlatformBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      platform_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.Int32Value type_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> typeBuilder_;
    /**
     * <pre>
     * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
     * 兼容3.0测量协议 device_type 为 string enums
     * </pre>
     *
     * <code>.google.protobuf.Int32Value type = 4;</code>
     * @return Whether the type field is set.
     */
    public boolean hasType() {
      return typeBuilder_ != null || type_ != null;
    }
    /**
     * <pre>
     * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
     * 兼容3.0测量协议 device_type 为 string enums
     * </pre>
     *
     * <code>.google.protobuf.Int32Value type = 4;</code>
     * @return The type.
     */
    public com.google.protobuf.Int32Value getType() {
      if (typeBuilder_ == null) {
        return type_ == null ? com.google.protobuf.Int32Value.getDefaultInstance() : type_;
      } else {
        return typeBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
     * 兼容3.0测量协议 device_type 为 string enums
     * </pre>
     *
     * <code>.google.protobuf.Int32Value type = 4;</code>
     */
    public Builder setType(com.google.protobuf.Int32Value value) {
      if (typeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        type_ = value;
        onChanged();
      } else {
        typeBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
     * 兼容3.0测量协议 device_type 为 string enums
     * </pre>
     *
     * <code>.google.protobuf.Int32Value type = 4;</code>
     */
    public Builder setType(
        com.google.protobuf.Int32Value.Builder builderForValue) {
      if (typeBuilder_ == null) {
        type_ = builderForValue.build();
        onChanged();
      } else {
        typeBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
     * 兼容3.0测量协议 device_type 为 string enums
     * </pre>
     *
     * <code>.google.protobuf.Int32Value type = 4;</code>
     */
    public Builder mergeType(com.google.protobuf.Int32Value value) {
      if (typeBuilder_ == null) {
        if (type_ != null) {
          type_ =
            com.google.protobuf.Int32Value.newBuilder(type_).mergeFrom(value).buildPartial();
        } else {
          type_ = value;
        }
        onChanged();
      } else {
        typeBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
     * 兼容3.0测量协议 device_type 为 string enums
     * </pre>
     *
     * <code>.google.protobuf.Int32Value type = 4;</code>
     */
    public Builder clearType() {
      if (typeBuilder_ == null) {
        type_ = null;
        onChanged();
      } else {
        type_ = null;
        typeBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
     * 兼容3.0测量协议 device_type 为 string enums
     * </pre>
     *
     * <code>.google.protobuf.Int32Value type = 4;</code>
     */
    public com.google.protobuf.Int32Value.Builder getTypeBuilder() {
      
      onChanged();
      return getTypeFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
     * 兼容3.0测量协议 device_type 为 string enums
     * </pre>
     *
     * <code>.google.protobuf.Int32Value type = 4;</code>
     */
    public com.google.protobuf.Int32ValueOrBuilder getTypeOrBuilder() {
      if (typeBuilder_ != null) {
        return typeBuilder_.getMessageOrBuilder();
      } else {
        return type_ == null ?
            com.google.protobuf.Int32Value.getDefaultInstance() : type_;
      }
    }
    /**
     * <pre>
     * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
     * 兼容3.0测量协议 device_type 为 string enums
     * </pre>
     *
     * <code>.google.protobuf.Int32Value type = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder> 
        getTypeFieldBuilder() {
      if (typeBuilder_ == null) {
        typeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Int32Value, com.google.protobuf.Int32Value.Builder, com.google.protobuf.Int32ValueOrBuilder>(
                getType(),
                getParentForChildren(),
                isClean());
        type_ = null;
      }
      return typeBuilder_;
    }

    private java.lang.Object imei_ = "";
    /**
     * <code>string imei = 5;</code>
     * @return The imei.
     */
    public java.lang.String getImei() {
      java.lang.Object ref = imei_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        imei_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string imei = 5;</code>
     * @return The bytes for imei.
     */
    public com.google.protobuf.ByteString
        getImeiBytes() {
      java.lang.Object ref = imei_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        imei_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string imei = 5;</code>
     * @param value The imei to set.
     * @return This builder for chaining.
     */
    public Builder setImei(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      imei_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string imei = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearImei() {
      
      imei_ = getDefaultInstance().getImei();
      onChanged();
      return this;
    }
    /**
     * <code>string imei = 5;</code>
     * @param value The bytes for imei to set.
     * @return This builder for chaining.
     */
    public Builder setImeiBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      imei_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object androidId_ = "";
    /**
     * <code>string android_id = 6;</code>
     * @return The androidId.
     */
    public java.lang.String getAndroidId() {
      java.lang.Object ref = androidId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        androidId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string android_id = 6;</code>
     * @return The bytes for androidId.
     */
    public com.google.protobuf.ByteString
        getAndroidIdBytes() {
      java.lang.Object ref = androidId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        androidId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string android_id = 6;</code>
     * @param value The androidId to set.
     * @return This builder for chaining.
     */
    public Builder setAndroidId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      androidId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string android_id = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearAndroidId() {
      
      androidId_ = getDefaultInstance().getAndroidId();
      onChanged();
      return this;
    }
    /**
     * <code>string android_id = 6;</code>
     * @param value The bytes for androidId to set.
     * @return This builder for chaining.
     */
    public Builder setAndroidIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      androidId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object oaid_ = "";
    /**
     * <code>string oaid = 7;</code>
     * @return The oaid.
     */
    public java.lang.String getOaid() {
      java.lang.Object ref = oaid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        oaid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string oaid = 7;</code>
     * @return The bytes for oaid.
     */
    public com.google.protobuf.ByteString
        getOaidBytes() {
      java.lang.Object ref = oaid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        oaid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string oaid = 7;</code>
     * @param value The oaid to set.
     * @return This builder for chaining.
     */
    public Builder setOaid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      oaid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string oaid = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearOaid() {
      
      oaid_ = getDefaultInstance().getOaid();
      onChanged();
      return this;
    }
    /**
     * <code>string oaid = 7;</code>
     * @param value The bytes for oaid to set.
     * @return This builder for chaining.
     */
    public Builder setOaidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      oaid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object googleAdvertisingId_ = "";
    /**
     * <code>string google_advertising_id = 8;</code>
     * @return The googleAdvertisingId.
     */
    public java.lang.String getGoogleAdvertisingId() {
      java.lang.Object ref = googleAdvertisingId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        googleAdvertisingId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string google_advertising_id = 8;</code>
     * @return The bytes for googleAdvertisingId.
     */
    public com.google.protobuf.ByteString
        getGoogleAdvertisingIdBytes() {
      java.lang.Object ref = googleAdvertisingId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        googleAdvertisingId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string google_advertising_id = 8;</code>
     * @param value The googleAdvertisingId to set.
     * @return This builder for chaining.
     */
    public Builder setGoogleAdvertisingId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      googleAdvertisingId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string google_advertising_id = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearGoogleAdvertisingId() {
      
      googleAdvertisingId_ = getDefaultInstance().getGoogleAdvertisingId();
      onChanged();
      return this;
    }
    /**
     * <code>string google_advertising_id = 8;</code>
     * @param value The bytes for googleAdvertisingId to set.
     * @return This builder for chaining.
     */
    public Builder setGoogleAdvertisingIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      googleAdvertisingId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object idfa_ = "";
    /**
     * <code>string idfa = 9;</code>
     * @return The idfa.
     */
    public java.lang.String getIdfa() {
      java.lang.Object ref = idfa_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idfa_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idfa = 9;</code>
     * @return The bytes for idfa.
     */
    public com.google.protobuf.ByteString
        getIdfaBytes() {
      java.lang.Object ref = idfa_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idfa_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idfa = 9;</code>
     * @param value The idfa to set.
     * @return This builder for chaining.
     */
    public Builder setIdfa(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      idfa_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string idfa = 9;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdfa() {
      
      idfa_ = getDefaultInstance().getIdfa();
      onChanged();
      return this;
    }
    /**
     * <code>string idfa = 9;</code>
     * @param value The bytes for idfa to set.
     * @return This builder for chaining.
     */
    public Builder setIdfaBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      idfa_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object idfv_ = "";
    /**
     * <code>string idfv = 10;</code>
     * @return The idfv.
     */
    public java.lang.String getIdfv() {
      java.lang.Object ref = idfv_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        idfv_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string idfv = 10;</code>
     * @return The bytes for idfv.
     */
    public com.google.protobuf.ByteString
        getIdfvBytes() {
      java.lang.Object ref = idfv_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        idfv_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string idfv = 10;</code>
     * @param value The idfv to set.
     * @return This builder for chaining.
     */
    public Builder setIdfv(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      idfv_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string idfv = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearIdfv() {
      
      idfv_ = getDefaultInstance().getIdfv();
      onChanged();
      return this;
    }
    /**
     * <code>string idfv = 10;</code>
     * @param value The bytes for idfv to set.
     * @return This builder for chaining.
     */
    public Builder setIdfvBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      idfv_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object deviceType_ = "";
    /**
     * <code>string device_type = 11;</code>
     * @return The deviceType.
     */
    public java.lang.String getDeviceType() {
      java.lang.Object ref = deviceType_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        deviceType_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string device_type = 11;</code>
     * @return The bytes for deviceType.
     */
    public com.google.protobuf.ByteString
        getDeviceTypeBytes() {
      java.lang.Object ref = deviceType_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deviceType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string device_type = 11;</code>
     * @param value The deviceType to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      deviceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string device_type = 11;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeviceType() {
      
      deviceType_ = getDefaultInstance().getDeviceType();
      onChanged();
      return this;
    }
    /**
     * <code>string device_type = 11;</code>
     * @param value The bytes for deviceType to set.
     * @return This builder for chaining.
     */
    public Builder setDeviceTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      deviceType_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:io.growing.tunnel.protocol.DeviceDto)
  }

  // @@protoc_insertion_point(class_scope:io.growing.tunnel.protocol.DeviceDto)
  private static final io.growing.collector.tunnel.protocol.DeviceDto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.growing.collector.tunnel.protocol.DeviceDto();
  }

  public static io.growing.collector.tunnel.protocol.DeviceDto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<DeviceDto>
      PARSER = new com.google.protobuf.AbstractParser<DeviceDto>() {
    @java.lang.Override
    public DeviceDto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new DeviceDto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<DeviceDto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<DeviceDto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.growing.collector.tunnel.protocol.DeviceDto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

