// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: context.proto

package io.growing.collector.tunnel.protocol;

public interface DeviceDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.growing.tunnel.protocol.DeviceDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string brand = 1;</code>
   * @return The brand.
   */
  java.lang.String getBrand();
  /**
   * <code>string brand = 1;</code>
   * @return The bytes for brand.
   */
  com.google.protobuf.ByteString
      getBrandBytes();

  /**
   * <code>string model = 2;</code>
   * @return The model.
   */
  java.lang.String getModel();
  /**
   * <code>string model = 2;</code>
   * @return The bytes for model.
   */
  com.google.protobuf.ByteString
      getModelBytes();

  /**
   * <code>string platform = 3;</code>
   * @return The platform.
   */
  java.lang.String getPlatform();
  /**
   * <code>string platform = 3;</code>
   * @return The bytes for platform.
   */
  com.google.protobuf.ByteString
      getPlatformBytes();

  /**
   * <pre>
   * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
   * 兼容3.0测量协议 device_type 为 string enums
   * </pre>
   *
   * <code>.google.protobuf.Int32Value type = 4;</code>
   * @return Whether the type field is set.
   */
  boolean hasType();
  /**
   * <pre>
   * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
   * 兼容3.0测量协议 device_type 为 string enums
   * </pre>
   *
   * <code>.google.protobuf.Int32Value type = 4;</code>
   * @return The type.
   */
  com.google.protobuf.Int32Value getType();
  /**
   * <pre>
   * https://growingio.atlassian.net/wiki/spaces/SDK/pages/1850146836/MinP+SDK+Measurement+Protocol+3.0
   * 兼容3.0测量协议 device_type 为 string enums
   * </pre>
   *
   * <code>.google.protobuf.Int32Value type = 4;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getTypeOrBuilder();

  /**
   * <code>string imei = 5;</code>
   * @return The imei.
   */
  java.lang.String getImei();
  /**
   * <code>string imei = 5;</code>
   * @return The bytes for imei.
   */
  com.google.protobuf.ByteString
      getImeiBytes();

  /**
   * <code>string android_id = 6;</code>
   * @return The androidId.
   */
  java.lang.String getAndroidId();
  /**
   * <code>string android_id = 6;</code>
   * @return The bytes for androidId.
   */
  com.google.protobuf.ByteString
      getAndroidIdBytes();

  /**
   * <code>string oaid = 7;</code>
   * @return The oaid.
   */
  java.lang.String getOaid();
  /**
   * <code>string oaid = 7;</code>
   * @return The bytes for oaid.
   */
  com.google.protobuf.ByteString
      getOaidBytes();

  /**
   * <code>string google_advertising_id = 8;</code>
   * @return The googleAdvertisingId.
   */
  java.lang.String getGoogleAdvertisingId();
  /**
   * <code>string google_advertising_id = 8;</code>
   * @return The bytes for googleAdvertisingId.
   */
  com.google.protobuf.ByteString
      getGoogleAdvertisingIdBytes();

  /**
   * <code>string idfa = 9;</code>
   * @return The idfa.
   */
  java.lang.String getIdfa();
  /**
   * <code>string idfa = 9;</code>
   * @return The bytes for idfa.
   */
  com.google.protobuf.ByteString
      getIdfaBytes();

  /**
   * <code>string idfv = 10;</code>
   * @return The idfv.
   */
  java.lang.String getIdfv();
  /**
   * <code>string idfv = 10;</code>
   * @return The bytes for idfv.
   */
  com.google.protobuf.ByteString
      getIdfvBytes();

  /**
   * <code>string device_type = 11;</code>
   * @return The deviceType.
   */
  java.lang.String getDeviceType();
  /**
   * <code>string device_type = 11;</code>
   * @return The bytes for deviceType.
   */
  com.google.protobuf.ByteString
      getDeviceTypeBytes();
}
