// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package io.growing.collector.tunnel.protocol;

public final class EventProtocol {
  private EventProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_EventDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_EventDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_EventDto_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_EventDto_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_EventList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_EventList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013event.proto\022\032io.growing.tunnel.protoco" +
      "l\032\024v1/dto/context.proto\032\021v1/dto/item.pro" +
      "to\"\366\005\n\010EventDto\022\024\n\014anonymous_id\030\001 \001(\t\022\023\n" +
      "\013project_key\030\002 \001(\t\022\017\n\007user_id\030\003 \001(\t\022\016\n\006g" +
      "io_id\030\004 \001(\t\022\021\n\ttimestamp\030\005 \001(\003\022\014\n\004esid\030\006" +
      " \001(\005\022\017\n\007session\030\007 \001(\t\022\021\n\tevent_key\030\010 \001(\t" +
      "\022<\n\004type\030\t \001(\0162..io.growing.tunnel.proto" +
      "col.EventDto.EventType\022\017\n\007version\030\n \001(\t\022" +
      "\n\n\002ip\030\013 \001(\t\0227\n\007context\030\014 \001(\0132&.io.growin" +
      "g.tunnel.protocol.ContextDto\022H\n\nattribut" +
      "es\030\r \003(\01324.io.growing.tunnel.protocol.Ev" +
      "entDto.AttributesEntry\022\021\n\tsend_time\030\016 \001(" +
      "\003\022\021\n\tevent_num\030\017 \001(\001\022\026\n\016data_source_id\030\020" +
      " \001(\t\0221\n\004item\030\021 \001(\0132#.io.growing.tunnel.p" +
      "rotocol.ItemDto\022\033\n\023page_show_timestamp\030\022" +
      " \001(\003\022\022\n\ntext_value\030\023 \001(\t\022\r\n\005xpath\030\024 \001(\t\022" +
      "\r\n\005index\030\025 \001(\005\022\021\n\thyperlink\030\026 \001(\t\0321\n\017Att" +
      "ributesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t" +
      ":\0028\001\"u\n\tEventType\022\t\n\005VISIT\020\000\022\020\n\014CUSTOM_E" +
      "VENT\020\001\022\010\n\004PAGE\020\002\022\017\n\013VISIT_CLOSE\020\003\022\016\n\nVIE" +
      "W_CLICK\020\004\022\017\n\013VIEW_CHANGE\020\005\022\017\n\013FORM_SUBMI" +
      "T\020\006\"A\n\tEventList\0224\n\006values\030\001 \003(\0132$.io.gr" +
      "owing.tunnel.protocol.EventDtoB7\n$io.gro" +
      "wing.collector.tunnel.protocolB\rEventPro" +
      "tocolP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.growing.collector.tunnel.protocol.ContextProtocol.getDescriptor(),
          io.growing.collector.tunnel.protocol.ItemProtocol.getDescriptor(),
        });
    internal_static_io_growing_tunnel_protocol_EventDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_growing_tunnel_protocol_EventDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_EventDto_descriptor,
        new java.lang.String[] { "AnonymousId", "ProjectKey", "UserId", "GioId", "Timestamp", "Esid", "Session", "EventKey", "Type", "Version", "Ip", "Context", "Attributes", "SendTime", "EventNum", "DataSourceId", "Item", "PageShowTimestamp", "TextValue", "Xpath", "Index", "Hyperlink", });
    internal_static_io_growing_tunnel_protocol_EventDto_AttributesEntry_descriptor =
      internal_static_io_growing_tunnel_protocol_EventDto_descriptor.getNestedTypes().get(0);
    internal_static_io_growing_tunnel_protocol_EventDto_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_EventDto_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_io_growing_tunnel_protocol_EventList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_growing_tunnel_protocol_EventList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_EventList_descriptor,
        new java.lang.String[] { "Values", });
    io.growing.collector.tunnel.protocol.ContextProtocol.getDescriptor();
    io.growing.collector.tunnel.protocol.ItemProtocol.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
