// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package io.growing.collector.tunnel.protocol;

public interface EventDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.growing.tunnel.protocol.EventDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string anonymous_id = 1;</code>
   * @return The anonymousId.
   */
  java.lang.String getAnonymousId();
  /**
   * <code>string anonymous_id = 1;</code>
   * @return The bytes for anonymousId.
   */
  com.google.protobuf.ByteString
      getAnonymousIdBytes();

  /**
   * <pre>
   * required
   * </pre>
   *
   * <code>string project_key = 2;</code>
   * @return The projectKey.
   */
  java.lang.String getProjectKey();
  /**
   * <pre>
   * required
   * </pre>
   *
   * <code>string project_key = 2;</code>
   * @return The bytes for projectKey.
   */
  com.google.protobuf.ByteString
      getProjectKeyBytes();

  /**
   * <code>string user_id = 3;</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 3;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string gio_id = 4;</code>
   * @return The gioId.
   */
  java.lang.String getGioId();
  /**
   * <code>string gio_id = 4;</code>
   * @return The bytes for gioId.
   */
  com.google.protobuf.ByteString
      getGioIdBytes();

  /**
   * <pre>
   * required
   * </pre>
   *
   * <code>int64 timestamp = 5;</code>
   * @return The timestamp.
   */
  long getTimestamp();

  /**
   * <code>int32 esid = 6;</code>
   * @return The esid.
   */
  int getEsid();

  /**
   * <code>string session = 7;</code>
   * @return The session.
   */
  java.lang.String getSession();
  /**
   * <code>string session = 7;</code>
   * @return The bytes for session.
   */
  com.google.protobuf.ByteString
      getSessionBytes();

  /**
   * <pre>
   * required
   * </pre>
   *
   * <code>string event_key = 8;</code>
   * @return The eventKey.
   */
  java.lang.String getEventKey();
  /**
   * <pre>
   * required
   * </pre>
   *
   * <code>string event_key = 8;</code>
   * @return The bytes for eventKey.
   */
  com.google.protobuf.ByteString
      getEventKeyBytes();

  /**
   * <pre>
   * required
   * </pre>
   *
   * <code>.io.growing.tunnel.protocol.EventDto.EventType type = 9;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * required
   * </pre>
   *
   * <code>.io.growing.tunnel.protocol.EventDto.EventType type = 9;</code>
   * @return The type.
   */
  io.growing.collector.tunnel.protocol.EventDto.EventType getType();

  /**
   * <pre>
   * required
   * </pre>
   *
   * <code>string version = 10;</code>
   * @return The version.
   */
  java.lang.String getVersion();
  /**
   * <pre>
   * required
   * </pre>
   *
   * <code>string version = 10;</code>
   * @return The bytes for version.
   */
  com.google.protobuf.ByteString
      getVersionBytes();

  /**
   * <code>string ip = 11;</code>
   * @return The ip.
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 11;</code>
   * @return The bytes for ip.
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>.io.growing.tunnel.protocol.ContextDto context = 12;</code>
   * @return Whether the context field is set.
   */
  boolean hasContext();
  /**
   * <code>.io.growing.tunnel.protocol.ContextDto context = 12;</code>
   * @return The context.
   */
  io.growing.collector.tunnel.protocol.ContextDto getContext();
  /**
   * <code>.io.growing.tunnel.protocol.ContextDto context = 12;</code>
   */
  io.growing.collector.tunnel.protocol.ContextDtoOrBuilder getContextOrBuilder();

  /**
   * <code>map&lt;string, string&gt; attributes = 13;</code>
   */
  int getAttributesCount();
  /**
   * <code>map&lt;string, string&gt; attributes = 13;</code>
   */
  boolean containsAttributes(
      java.lang.String key);
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAttributes();
  /**
   * <code>map&lt;string, string&gt; attributes = 13;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAttributesMap();
  /**
   * <code>map&lt;string, string&gt; attributes = 13;</code>
   */

  java.lang.String getAttributesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; attributes = 13;</code>
   */

  java.lang.String getAttributesOrThrow(
      java.lang.String key);

  /**
   * <code>int64 send_time = 14;</code>
   * @return The sendTime.
   */
  long getSendTime();

  /**
   * <code>double event_num = 15;</code>
   * @return The eventNum.
   */
  double getEventNum();

  /**
   * <code>string data_source_id = 16;</code>
   * @return The dataSourceId.
   */
  java.lang.String getDataSourceId();
  /**
   * <code>string data_source_id = 16;</code>
   * @return The bytes for dataSourceId.
   */
  com.google.protobuf.ByteString
      getDataSourceIdBytes();

  /**
   * <code>.io.growing.tunnel.protocol.ItemDto item = 17;</code>
   * @return Whether the item field is set.
   */
  boolean hasItem();
  /**
   * <code>.io.growing.tunnel.protocol.ItemDto item = 17;</code>
   * @return The item.
   */
  io.growing.collector.tunnel.protocol.ItemDto getItem();
  /**
   * <code>.io.growing.tunnel.protocol.ItemDto item = 17;</code>
   */
  io.growing.collector.tunnel.protocol.ItemDtoOrBuilder getItemOrBuilder();

  /**
   * <code>int64 page_show_timestamp = 18;</code>
   * @return The pageShowTimestamp.
   */
  long getPageShowTimestamp();

  /**
   * <code>string text_value = 19;</code>
   * @return The textValue.
   */
  java.lang.String getTextValue();
  /**
   * <code>string text_value = 19;</code>
   * @return The bytes for textValue.
   */
  com.google.protobuf.ByteString
      getTextValueBytes();

  /**
   * <code>string xpath = 20;</code>
   * @return The xpath.
   */
  java.lang.String getXpath();
  /**
   * <code>string xpath = 20;</code>
   * @return The bytes for xpath.
   */
  com.google.protobuf.ByteString
      getXpathBytes();

  /**
   * <code>int32 index = 21;</code>
   * @return The index.
   */
  int getIndex();

  /**
   * <code>string hyperlink = 22;</code>
   * @return The hyperlink.
   */
  java.lang.String getHyperlink();
  /**
   * <code>string hyperlink = 22;</code>
   * @return The bytes for hyperlink.
   */
  com.google.protobuf.ByteString
      getHyperlinkBytes();
}
