// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: event.proto

package io.growing.collector.tunnel.protocol;

public interface EventListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.growing.tunnel.protocol.EventList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.growing.tunnel.protocol.EventDto values = 1;</code>
   */
  java.util.List<io.growing.collector.tunnel.protocol.EventDto> 
      getValuesList();
  /**
   * <code>repeated .io.growing.tunnel.protocol.EventDto values = 1;</code>
   */
  io.growing.collector.tunnel.protocol.EventDto getValues(int index);
  /**
   * <code>repeated .io.growing.tunnel.protocol.EventDto values = 1;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .io.growing.tunnel.protocol.EventDto values = 1;</code>
   */
  java.util.List<? extends io.growing.collector.tunnel.protocol.EventDtoOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .io.growing.tunnel.protocol.EventDto values = 1;</code>
   */
  io.growing.collector.tunnel.protocol.EventDtoOrBuilder getValuesOrBuilder(
      int index);
}
