// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: item.proto

package io.growing.collector.tunnel.protocol;

public final class ItemProtocol {
  private ItemProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_ItemDto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_ItemDto_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_ItemDto_AttributesEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_ItemDto_AttributesEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_tunnel_protocol_ItemDtoList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_tunnel_protocol_ItemDtoList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nitem.proto\022\032io.growing.tunnel.protocol" +
      "\"\313\001\n\007ItemDto\022\n\n\002id\030\001 \001(\t\022\013\n\003key\030\002 \001(\t\022G\n" +
      "\nattributes\030\003 \003(\01323.io.growing.tunnel.pr" +
      "otocol.ItemDto.AttributesEntry\022\026\n\016data_s" +
      "ource_id\030\004 \001(\t\022\023\n\013project_key\030\005 \001(\t\0321\n\017A" +
      "ttributesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001" +
      "(\t:\0028\001\"B\n\013ItemDtoList\0223\n\006values\030\002 \003(\0132#." +
      "io.growing.tunnel.protocol.ItemDtoB6\n$io" +
      ".growing.collector.tunnel.protocolB\014Item" +
      "ProtocolP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_growing_tunnel_protocol_ItemDto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_growing_tunnel_protocol_ItemDto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_ItemDto_descriptor,
        new java.lang.String[] { "Id", "Key", "Attributes", "DataSourceId", "ProjectKey", });
    internal_static_io_growing_tunnel_protocol_ItemDto_AttributesEntry_descriptor =
      internal_static_io_growing_tunnel_protocol_ItemDto_descriptor.getNestedTypes().get(0);
    internal_static_io_growing_tunnel_protocol_ItemDto_AttributesEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_ItemDto_AttributesEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_io_growing_tunnel_protocol_ItemDtoList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_growing_tunnel_protocol_ItemDtoList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_tunnel_protocol_ItemDtoList_descriptor,
        new java.lang.String[] { "Values", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
