// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: item.proto

package io.growing.collector.tunnel.protocol;

public interface ItemDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.growing.tunnel.protocol.ItemDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string key = 2;</code>
   * @return The key.
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   * @return The bytes for key.
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>map&lt;string, string&gt; attributes = 3;</code>
   */
  int getAttributesCount();
  /**
   * <code>map&lt;string, string&gt; attributes = 3;</code>
   */
  boolean containsAttributes(
      java.lang.String key);
  /**
   * Use {@link #getAttributesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAttributes();
  /**
   * <code>map&lt;string, string&gt; attributes = 3;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAttributesMap();
  /**
   * <code>map&lt;string, string&gt; attributes = 3;</code>
   */

  java.lang.String getAttributesOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; attributes = 3;</code>
   */

  java.lang.String getAttributesOrThrow(
      java.lang.String key);

  /**
   * <code>string data_source_id = 4;</code>
   * @return The dataSourceId.
   */
  java.lang.String getDataSourceId();
  /**
   * <code>string data_source_id = 4;</code>
   * @return The bytes for dataSourceId.
   */
  com.google.protobuf.ByteString
      getDataSourceIdBytes();

  /**
   * <code>string project_key = 5;</code>
   * @return The projectKey.
   */
  java.lang.String getProjectKey();
  /**
   * <code>string project_key = 5;</code>
   * @return The bytes for projectKey.
   */
  com.google.protobuf.ByteString
      getProjectKeyBytes();
}
