// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: item.proto

package io.growing.collector.tunnel.protocol;

public interface ItemDtoListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.growing.tunnel.protocol.ItemDtoList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .io.growing.tunnel.protocol.ItemDto values = 2;</code>
   */
  java.util.List<io.growing.collector.tunnel.protocol.ItemDto> 
      getValuesList();
  /**
   * <code>repeated .io.growing.tunnel.protocol.ItemDto values = 2;</code>
   */
  io.growing.collector.tunnel.protocol.ItemDto getValues(int index);
  /**
   * <code>repeated .io.growing.tunnel.protocol.ItemDto values = 2;</code>
   */
  int getValuesCount();
  /**
   * <code>repeated .io.growing.tunnel.protocol.ItemDto values = 2;</code>
   */
  java.util.List<? extends io.growing.collector.tunnel.protocol.ItemDtoOrBuilder> 
      getValuesOrBuilderList();
  /**
   * <code>repeated .io.growing.tunnel.protocol.ItemDto values = 2;</code>
   */
  io.growing.collector.tunnel.protocol.ItemDtoOrBuilder getValuesOrBuilder(
      int index);
}
