// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: context.proto

package io.growing.collector.tunnel.protocol;

public interface LocationDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.growing.tunnel.protocol.LocationDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double longitude = 1;</code>
   * @return The longitude.
   */
  double getLongitude();

  /**
   * <code>double latitude = 2;</code>
   * @return The latitude.
   */
  double getLatitude();
}
