// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: context.proto

package io.growing.collector.tunnel.protocol;

public interface LocaleDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.growing.tunnel.protocol.LocaleDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string language = 1;</code>
   * @return The language.
   */
  java.lang.String getLanguage();
  /**
   * <code>string language = 1;</code>
   * @return The bytes for language.
   */
  com.google.protobuf.ByteString
      getLanguageBytes();

  /**
   * <code>string timezone = 2;</code>
   * @return The timezone.
   */
  java.lang.String getTimezone();
  /**
   * <code>string timezone = 2;</code>
   * @return The bytes for timezone.
   */
  com.google.protobuf.ByteString
      getTimezoneBytes();
}
