// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: context.proto

package io.growing.collector.tunnel.protocol;

public interface NetworkDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.growing.tunnel.protocol.NetworkDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string carrier = 2;</code>
   * @return The carrier.
   */
  java.lang.String getCarrier();
  /**
   * <code>string carrier = 2;</code>
   * @return The bytes for carrier.
   */
  com.google.protobuf.ByteString
      getCarrierBytes();
}
