// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: context.proto

package io.growing.collector.tunnel.protocol;

public interface ReferrerDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.growing.tunnel.protocol.ReferrerDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string from = 1;</code>
   * @return The from.
   */
  java.lang.String getFrom();
  /**
   * <code>string from = 1;</code>
   * @return The bytes for from.
   */
  com.google.protobuf.ByteString
      getFromBytes();

  /**
   * <code>string page = 2;</code>
   * @return The page.
   */
  java.lang.String getPage();
  /**
   * <code>string page = 2;</code>
   * @return The bytes for page.
   */
  com.google.protobuf.ByteString
      getPageBytes();
}
