// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: context.proto

package io.growing.collector.tunnel.protocol;

public interface ScreenDtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.growing.tunnel.protocol.ScreenDto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 width = 1;</code>
   * @return The width.
   */
  int getWidth();

  /**
   * <code>int32 height = 2;</code>
   * @return The height.
   */
  int getHeight();

  /**
   * <code>int32 density = 3;</code>
   * @return The density.
   */
  int getDensity();

  /**
   * <code>.io.growing.tunnel.protocol.ScreenDto.Orientation orientation = 4;</code>
   * @return The enum numeric value on the wire for orientation.
   */
  int getOrientationValue();
  /**
   * <code>.io.growing.tunnel.protocol.ScreenDto.Orientation orientation = 4;</code>
   * @return The orientation.
   */
  io.growing.collector.tunnel.protocol.ScreenDto.Orientation getOrientation();
}
