build:
  retry:
    max: 2
    when: always
  stage: build
  tags:
    - shell
  script:
    - "cd spark-egg-roll"
    - "mvn package -DpackageName=gio-dc-batch-$CI_COMMIT_BRANCH-$CI_JOB_ID-$CI_COMMIT_SHORT_SHA -Passembly -DskipTests=true"
    - "cd .."
    - "mkdir dist"
    - "mkdir dist/batch"
    - "mkdir dist/airflow"
    - "mkdir dist/sql"
    - "cp -r sql/* dist/sql/"
    - "cp -r airflow/* dist/airflow/"
    - "cp -r init dist/"
    - "cp cdp.yml dist/"
    - "mv dist gio-dc-etl-$CI_COMMIT_BRANCH-$CI_JOB_ID-$CI_COMMIT_SHORT_SHA"
    - "tar -zcvf gio-dc-etl-$CI_COMMIT_BRANCH-$CI_JOB_ID-$CI_COMMIT_SHORT_SHA.tar.gz gio-dc-etl-$CI_COMMIT_BRANCH-$CI_JOB_ID-$CI_COMMIT_SHORT_SHA"
    - "/usr/local/bin/aws s3 cp gio-dc-etl-$CI_COMMIT_BRANCH-$CI_JOB_ID-$CI_COMMIT_SHORT_SHA.tar.gz s3://growingio-cdp-packages/snapshot/gio-dc-etl/$CI_COMMIT_BRANCH/"


after_script:
  - "rm -rf $CI_PROJECT_DIR"