// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomEvent.proto

package io.growing.validator.tunnel.protocol;

public final class CustomEvent {
  private CustomEvent() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_growing_validator_tunnel_protocol_CustomEventMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_growing_validator_tunnel_protocol_CustomEventMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021CustomEvent.proto\022$io.growing.validato" +
      "r.tunnel.protocol\"J\n\022CustomEventMessage\022" +
      "\022\n\nprojectKey\030\001 \001(\t\022\021\n\tattribute\030\002 \001(\t\022\r" +
      "\n\005email\030\003 \001(\tB5\n$io.growing.validator.tu" +
      "nnel.protocolB\013CustomEventP\001"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_growing_validator_tunnel_protocol_CustomEventMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_growing_validator_tunnel_protocol_CustomEventMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_growing_validator_tunnel_protocol_CustomEventMessage_descriptor,
        new java.lang.String[] { "ProjectKey", "Attribute", "Email", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
