// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CustomEvent.proto

package io.growing.validator.tunnel.protocol;

public interface CustomEventMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.growing.validator.tunnel.protocol.CustomEventMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string projectKey = 1;</code>
   * @return Whether the projectKey field is set.
   */
  boolean hasProjectKey();
  /**
   * <code>optional string projectKey = 1;</code>
   * @return The projectKey.
   */
  java.lang.String getProjectKey();
  /**
   * <code>optional string projectKey = 1;</code>
   * @return The bytes for projectKey.
   */
  com.google.protobuf.ByteString
      getProjectKeyBytes();

  /**
   * <code>optional string attribute = 2;</code>
   * @return Whether the attribute field is set.
   */
  boolean hasAttribute();
  /**
   * <code>optional string attribute = 2;</code>
   * @return The attribute.
   */
  java.lang.String getAttribute();
  /**
   * <code>optional string attribute = 2;</code>
   * @return The bytes for attribute.
   */
  com.google.protobuf.ByteString
      getAttributeBytes();

  /**
   * <code>optional string email = 3;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();
}
